### ISSUE TITLE
Forbidden getting pod logs, IPv6

### ISSUE THREAD

**Issue by mconner** [canonical/microk8s#2104]
Please run `microk8s inspect` and attach the generated tarball to this issue.
[inspection-report-20210317_162607.tar.gz](https://github.com/ubuntu/microk8s/files/6157997/inspection-report-20210317_162607.tar.gz)

I've got a recent version of microk8s (snap tracking: 1.20/stable)  installed on a recent version of ubuntu (20.04.2 LTS (Focal Fossa)).
Till yesterday, I'm pretty sure I was able to do `kubectl logs pod-name`.  However now, I'm getting:
daruser@darqa:~$ kubectl logs -n ingress nginx-ingress-microk8s-controller-5xmb8
```
Error from server: Get "https://darqa:10250/containerLogs/ingress/nginx-ingress-microk8s-controller-5xmb8/nginx-ingress-microk8s": Forbidden
daruser@darqa:~$

```
If I do 
`kubectl logs -n ingress nginx-ingress-microk8s-controller-5xmb8 -v=9
`
I get:
```
...

I0317 16:37:02.102444 3840890 round_trippers.go:425] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.20.4 (linux/amd64) kubernetes/1ae8c29" -H "Authorization: Bearer <masked>" 'https://127.0.0.1:16443/api/v1/namespaces/ingress/pods/nginx-ingress-microk8s-controller-5xmb8/log'
I0317 16:37:02.122644 3840890 round_trippers.go:445] GET https://127.0.0.1:16443/api/v1/namespaces/ingress/pods/nginx-ingress-microk8s-controller-5xmb8/log 500 Internal Server Error in 20 milliseconds
I0317 16:37:02.122705 3840890 round_trippers.go:451] Response Headers:
I0317 16:37:02.122833 3840890 round_trippers.go:454]     Cache-Control: no-cache, private
I0317 16:37:02.122898 3840890 round_trippers.go:454]     Content-Type: application/json
I0317 16:37:02.123015 3840890 round_trippers.go:454]     Content-Length: 216
I0317 16:37:02.123044 3840890 round_trippers.go:454]     Date: Wed, 17 Mar 2021 16:37:02 GMT
I0317 16:37:02.123164 3840890 request.go:1107] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Get \"https://darqa:10250/containerLogs/ingress/nginx-ingress-microk8s-controller-5xmb8/nginx-ingress-microk8s\": Forbidden","code":500}
I0317 16:37:02.124355 3840890 helpers.go:216] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "Get \"https://darqa:10250/containerLogs/ingress/nginx-ingress-microk8s-controller-5xmb8/nginx-ingress-microk8s\": Forbidden",
  "code": 500
}]
F0317 16:37:02.124505 3840890 helpers.go:115] Error from server: Get "https://darqa:10250/containerLogs/ingress/nginx-ingress-microk8s-controller-5xmb8/nginx-ingress-microk8s": Forbidden
goroutine 1 [running]:
...

```

if I do `sudo netstat -tulpn`
The only line with port 10250 is an ipv6 address: 

```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:19001         0.0.0.0:*               LISTEN      3753204/kube-apiser
tcp        0      0 127.0.0.1:1338          0.0.0.0:*               LISTEN      3753239/containerd
tcp        0      0 127.0.0.1:34855         0.0.0.0:*               LISTEN      3753239/containerd
tcp        0      0 127.0.0.1:10248         0.0.0.0:*               LISTEN      3753299/kubelet
tcp        0      0 0.0.0.0:25000           0.0.0.0:*               LISTEN      3753400/python3
tcp        0      0 127.0.0.1:10249         0.0.0.0:*               LISTEN      3753307/kube-proxy
tcp        0      0 127.0.0.1:9099          0.0.0.0:*               LISTEN      3758883/calico-node
tcp        0      0 127.0.0.1:10251         0.0.0.0:*               LISTEN      3753326/kube-schedu
tcp        0      0 127.0.0.1:10252         0.0.0.0:*               LISTEN      3753257/kube-contro
tcp        0      0 0.0.0.0:30094           0.0.0.0:*               LISTEN      3753307/kube-proxy
tcp        0      0 127.0.0.1:10256         0.0.0.0:*               LISTEN      3753307/kube-proxy
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      985/systemd-resolve
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1740/sshd: /usr/sbi
tcp6       0      0 :::16443                :::*                    LISTEN      3753204/kube-apiser
tcp6       0      0 :::10250                :::*                    LISTEN      3753299/kubelet
tcp6       0      0 :::10255                :::*                    LISTEN      3753299/kubelet
tcp6       0      0 :::10257                :::*                    LISTEN      3753257/kube-contro
tcp6       0      0 :::10259                :::*                    LISTEN      3753326/kube-schedu
tcp6       0      0 :::22                   :::*                    LISTEN      1740/sshd: /usr/sbi
udp        0      0 127.0.0.53:53           0.0.0.0:*                           985/systemd-resolve
udp        0      0 0.0.0.0:4789            0.0.0.0:*                           -

```
darqa is in /etc/hosts as 
```
127.0.0.1 localhost
127.0.1.1 darqa
```

I don't know where to go from here, other than maybe disabling ipv6?

**Comment by balchua** [comment]
@mconner apologies for the trouble you are getting into.  Is disabling ipv6 work?  As far as i know there's some bit of work to do with regards to using ipv6.
Somebody wrote an article about using dual stack with MicroK8s.
https://github.com/ubuntu/microk8s/issues/1343#issuecomment-762630371
