### ISSUE TITLE
Jetson AGX Xavier: calico-node pod failing to run: Bad return code from ipset list - Kernel error received: Invalid argument

### ISSUE THREAD

**Issue by davecore82** [canonical/microk8s#2110]
calico fails to run on microk8s on an nvidia Jetson AGX Xavier:

```
ubuntu@xavier:~$ microk8s kubectl get pods,ds -n kube-system
NAME                                          READY   STATUS    RESTARTS   AGE
pod/calico-kube-controllers-847c8c99d-2g4nk   1/1     Running   0          81m
pod/calico-node-g8wvp                         0/1     Running   0          81m

NAME                         DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
daemonset.apps/calico-node   1         1         0       1            0           kubernetes.io/os=linux   81m
```

Here's a sample of the calico-node pod logs:

```
goroutine 172 [running]:
github.com/sirupsen/logrus.Entry.log(0x40000d0180, 0x400040d170, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/projectcalico/logrus@v1.0.4-calico/entry.go:128 +0x5d4
github.com/sirupsen/logrus.(*Entry).Panic(0x40003101e0, 0x40007dfbb8, 0x1, 0x1)
	/go/pkg/mod/github.com/projectcalico/logrus@v1.0.4-calico/entry.go:173 +0xb4
github.com/projectcalico/felix/ipsets.(*IPSets).ApplyUpdates(0x40002059e0)
	/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20200311115901-aa0a22d97c2d/ipsets/ipsets.go:342 +0x2bc
github.com/projectcalico/felix/dataplane/linux.(*InternalDataplane).apply.func1(0x40004ea500, 0x40005f1e70, 0x40002059e0)
	/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20200311115901-aa0a22d97c2d/dataplane/linux/int_dataplane.go:1290 +0x28
created by github.com/projectcalico/felix/dataplane/linux.(*InternalDataplane).apply
	/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20200311115901-aa0a22d97c2d/dataplane/linux/int_dataplane.go:1289 +0x310
2021-03-19 20:22:34.536 [ERROR][23453] ipsets.go 561: Bad return code from 'ipset list'. error=exit status 1 family="inet" stderr="ipset v6.38: Kernel error received: Invalid argument\n"
2021-03-19 20:22:34.544 [ERROR][23453] ipsets.go 561: Bad return code from 'ipset list'. error=exit status 1 family="inet" stderr="ipset v6.38: Kernel error received: Invalid argument\n"
2021-03-19 20:22:34.552 [ERROR][23453] ipsets.go 561: Bad return code from 'ipset list'. error=exit status 1 family="inet" stderr="ipset v6.38: Kernel error received: Invalid argument\n"
2021-03-19 20:22:34.563 [ERROR][23453] ipsets.go 561: Bad return code from 'ipset list'. error=exit status 1 family="inet" stderr="ipset v6.38: Kernel error received: Invalid argument\n"
2021-03-19 20:22:34.576 [ERROR][23453] ipsets.go 561: Bad return code from 'ipset list'. error=exit status 1 family="inet" stderr="ipset v6.38: Kernel error received: Invalid argument\n"
2021-03-19 20:22:34.599 [ERROR][23453] ipsets.go 561: Bad return code from 'ipset list'. error=exit status 1 family="inet" stderr="ipset v6.38: Kernel error received: Invalid argument\n"
2021-03-19 20:22:34.640 [ERROR][23453] ipsets.go 561: Bad return code from 'ipset list'. error=exit status 1 family="inet" stderr="ipset v6.38: Kernel error received: Invalid argument\n"
2021-03-19 20:22:34.710 [ERROR][23453] ipsets.go 561: Bad return code from 'ipset list'. error=exit status 1 family="inet" stderr="ipset v6.38: Kernel error received: Invalid argument\n"
2021-03-19 20:22:34.849 [ERROR][23453] ipsets.go 561: Bad return code from 'ipset list'. error=exit status 1 family="inet" stderr="ipset v6.38: Kernel error received: Invalid argument\n"
2021-03-19 20:22:35.114 [ERROR][23453] ipsets.go 561: Bad return code from 'ipset list'. error=exit status 1 family="inet" stderr="ipset v6.38: Kernel error received: Invalid argument\n"
2021-03-19 20:22:35.635 [ERROR][23453] ipsets.go 916: Failed to read IP sets error=exit status 1 family="inet"
2021-03-19 20:22:35.635 [PANIC][23453] ipsets.go 342: Failed to update IP sets after multiple retries. family="inet"
panic: (*logrus.Entry) (0x16a11e0,0x40008c6140)
```

The Jetson AGX Xavier is an ARM architecture unit, this one runs Ubuntu 18.04.5 LTS aarch64

```
ubuntu@xavier:~$ uname -a
Linux xavier 4.9.201-tegra #1 SMP PREEMPT Fri Feb 19 08:42:04 PST 2021 aarch64 aarch64 aarch64 GNU/Linux

ubuntu@xavier:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
```

Is it possible that calico doesn't support the 4.9 kernel on this Jetson unit?

`microk8s inspect` tarball

[inspection-report-20210319_213037.tar.gz](https://github.com/ubuntu/microk8s/files/6173937/inspection-report-20210319_213037.tar.gz)

**Comment by hlacik** [comment]
i can confirm that i am facing exactly same issue on jetson nano

2021-03-20 19:06:32.670 [ERROR][6756] ipsets.go 561: Bad return code from 'ipset list'. error=exit status 1 family="inet" stderr="ipset v6.38: Kernel error received: Invalid argument\n"

**Comment by balchua** [comment]
Did you try to use flannel?  In order to use flannel and etcd, you need to disable `microk8s disable ha-cluster`.

**Comment by hlacik** [comment]
> Did you try to use flannel? In order to use flannel and etcd, you need to disable `microk8s disable ha-cluster`.

yes, with flannel it works, callico apparently needs ipset module

only solution on jetson (l4t) platform is to custom compile kernel and enable modules needed for k8s

**Comment by balchua** [comment]
Thanks @hlacik for the info. Unfortunately I don't think there's anything MicroK8s can do here.

**Comment by ktsakalozos** [comment]
@davecore82 @hlacik this issue is reported to calico here https://github.com/projectcalico/felix/issues/2607.

Would upgrading the kernel be an option?

**Comment by hlacik** [comment]
> @davecore82 @hlacik this issue is reported to calico here [projectcalico/felix#2607](https://github.com/projectcalico/felix/issues/2607).
> 
> Would upgrading the kernel be an option?

well, nvidia-l4t linux distribution for jetson platform has custom kernel (4.9), luckily nvidia provides guide to rebuild custom kernel , so it is something i will have to do before going to production. For now, disabling ha-cluster and using flannel works .

**Comment by balchua** [comment]
Wrt to the gpu being enabled on arm arch, if we add it to the [`addon-list.yaml`](https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/wrappers/addon-lists.yaml) and rebuild the snap.
Then if you are keen, you can submit a PR. 😊

**Comment by davecore82** [comment]
> Did you try to use flannel? In order to use flannel and etcd, you need to disable `microk8s disable ha-cluster`.

Yes this is a good workaround for my use case, I don't need HA/clustering in this environment.

**Comment by hlacik** [comment]
> Then if you are keen, you can submit a PR.

@balchua well i have created this #2113  and it works!!

**Comment by giacinti** [comment]
Hello,
I know this is a quite old issue but from my experience, generating the missing module is not that a big deal and clearly fixes the issue. I gave it a try today on my Jetson Nano JetPack 4.6 and it works.
I used the procedure described here (Troubleshooting/Jetson Nano): https://github.com/tekn0ir/toe
My 2 cents

**Comment by giacinti** [comment]
Answering to myself - it seems another module is missing to have properly working calico-node on Jetson: ipip
For this one it is a bit more complicated as it is part of kernel and need to be configured as module in the source... but it is doable :-) good sources on how to do: https://developer.ridgerun.com/wiki/index.php?title=Jetson_Nano/Development/Building_the_Kernel_from_Source + https://docs.nvidia.com/jetson/archives/l4t-archived/l4t-3231/index.html#page/Tegra%2520Linux%2520Driver%2520Package%2520Development%2520Guide%2Fkernel_custom.html%23
It is recommended to get the sources from git (source_sync.sh) and sync to the correct tag (Eg: tegra-l4t-r32.6.1 for JetPack 4.6.1 = L4T 32-6-1)
