### ISSUE TITLE
Can't enable modules (Raspberry Pi OS Stretch ARM64)

### ISSUE THREAD

**Issue by SuperJMN** [canonical/microk8s#2305]
I've installed it using the latest Raspberry Pi OS for ARM64 on a Raspberry Pi 3 Model B.

It looks like it's installed and "running", but as soon as I try to enable any module, it fails to execute the given command.

For example, this is for DNS:

```
 microk8s enable dns
Traceback (most recent call last):
  File "/snap/microk8s/2217/scripts/wrappers/enable.py", line 43, in <module>
    enable(prog_name='microk8s enable')
  File "/snap/microk8s/2217/usr/lib/python3/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/snap/microk8s/2217/usr/lib/python3/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/snap/microk8s/2217/usr/lib/python3/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/microk8s/2217/usr/lib/python3/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/snap/microk8s/2217/scripts/wrappers/enable.py", line 36, in enable
    enabled_addons, _ = get_status(get_available_addons(get_current_arch()), True)
  File "/snap/microk8s/2217/scripts/wrappers/status.py", line 157, in get_status
    kube_output = kubectl_get("all")
  File "/snap/microk8s/2217/scripts/wrappers/common/utils.py", line 166, in kubectl_get
    return run("kubectl", kubeconfig, "get", cmd, "--all-namespaces", die=False)
  File "/snap/microk8s/2217/scripts/wrappers/common/utils.py", line 39, in run
    result.check_returncode()
  File "/snap/microk8s/2217/usr/lib/python3.5/subprocess.py", line 659, in check_returncode
    self.stderr)
subprocess.CalledProcessError: Command '('kubectl', '--kubeconfig=/var/snap/microk8s/2217/credentials/client.config', 'get', 'all', '--all-namespaces')' returned non-zero exit status 1
```

It happens the same with Dashboard.

## Inspection Report
[inspection-report-20210601_230905.tar.gz](https://github.com/ubuntu/microk8s/files/6580593/inspection-report-20210601_230905.tar.gz)

# Hardware
* Raspberry Pi  3 Model B (with 1 GB of RAM)
* Micro SD of 64 GB, 80% free.

Can someone, please, verify that microk8s is working in a Pi 3 like mine?

## Operating System
```
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 5.10.17-v8+ #1421 SMP PREEMPT Thu May 27 14:01:37 BST 2021 aarch64 GNU/Linux
```

## More info
I have tried with the latest Ubuntu Server for Raspberry Pi and I get the very same issue. I followed the official tutorial here: https://ubuntu.com/tutorials/how-to-kubernetes-cluster-on-raspberry-pi#1-overview

## Important
The official tutorial says that the minimum Pis required is 2. I guess this isn't strictly required, as this should also work with one Pi.

**Comment by balchua** [comment]
Pi 3B with 1GB ram?  Its probably crashing due to OOM.  You may get a bit of hope by enabling swap, but thats something kubernetes isn't recommending.

**Comment by SuperJMN** [comment]
Thanks for your answer! I've tried to increse the swapfile by using this guide:

https://pimylifeup.com/raspberry-pi-swap-file/

I've attached the inspection-report to the first message, too.

**Comment by ktsakalozos** [comment]
Looking briefly in the inspection tarball it seems MicroK8s started but it is working on the getting the CNI ready:
```
NAMESPACE     NAME                                          READY   STATUS     RESTARTS   AGE   IP              NODE          NOMINATED NODE   READINESS GATES
kube-system   pod/calico-kube-controllers-847c8c99d-9t82t   0/1     Pending    0          31m   <none>          <none>        <none>           <none>
kube-system   pod/calico-node-pkrb7                         0/1     Init:1/3   4          31m   192.168.1.133   raspberrypi   <none>           <none>
```

A source of issues we often find on RPis is the slow disk. What is your storage substrate? Have a look at the respective entry in the common issues section [1].

Something else you can try is to disable HA features so you can save up some resources. This is done with `microk8s disable ha-cluster`. Overall I am afraid you will straggle with this setup.

[1] https://microk8s.io/docs/troubleshooting#heading--common-issues

**Comment by SuperJMN** [comment]
After HA has been disabled, it finally was able to complete "enable dashboard", but now I have this problem:

![image](https://user-images.githubusercontent.com/3109851/120518462-e9060880-c3d1-11eb-9312-3144865f15a8.png)

It looks like Start doesn't really start it.

**Comment by balchua** [comment]
Imho, i find that rpi3 isn't going to play well with this, partly due to its resource needs. 🙁

**Comment by sed-i** [comment]
I observed a `CalledProcessError` on a [multipass blueprint](https://github.com/canonical/multipass-blueprints/blob/114aecc29ff4f4a2258b285d5c25c85ccfc0a7bc/v1/charm-dev.yaml#L92) when tried to enable the dns addon:

```
Traceback (most recent call last):
  File "/snap/microk8s/3052/scripts/wrappers/enable.py", line 43, in <module>
    enable(prog_name="microk8s enable")
  File "/snap/microk8s/3052/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/snap/microk8s/3052/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/snap/microk8s/3052/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/microk8s/3052/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/snap/microk8s/3052/scripts/wrappers/enable.py", line 36, in enable
    enabled_addons, _ = get_status(get_available_addons(get_current_arch()), True)
  File "/snap/microk8s/3052/scripts/wrappers/status.py", line 158, in get_status
    kube_output = kubectl_get("all,ingress")
  File "/snap/microk8s/3052/scripts/wrappers/common/utils.py", line 169, in kubectl_get
    return run("kubectl", kubeconfig, "get", cmd, "--all-namespaces", die=False)
  File "/snap/microk8s/3052/scripts/wrappers/common/utils.py", line 39, in run
    result.check_returncode()
  File "/snap/microk8s/3052/usr/lib/python3.6/subprocess.py", line 389, in check_returncode
    self.stderr)
subprocess.CalledProcessError: Command '('kubectl', '--kubeconfig=/var/snap/microk8s/3052/credentials/client.config', 'get', 'all,ingress', '--all-namespaces')' returned non-zero exit status 1.
The connection to the server 127.0.0.1:16443 was refused - did you specify the right host or port?
```

microk8s v1.23.5 on Ubuntu 20.04.4 on multipass (amd64).
