### ISSUE TITLE
Anybody ran this on a Raspberry Pi 3 successfully?

### ISSUE THREAD

**Issue by SuperJMN** [canonical/microk8s#2335]
I've been unable run MicroK8s in any of my Rpi3 (B+ included). I usually get this error:

> The connection to the server 127.0.0.1:16443 was refused

[inspection-report-20210612_233418.tar.gz](https://github.com/ubuntu/microk8s/files/6642938/inspection-report-20210612_233418.tar.gz)

Please, help us troubleshoot its setup in this hardware. I know there are many users that have had a hard time because of this.

Thanks in advance!

**Comment by ktsakalozos** [comment]
Hi @SuperJMN, getting kubernetes on a RP3 is going to be a challenge mainly due to the 1GB of memory you have available. You should always be wary of the memory usage available. Here is some configuration suggestions you could explore.

- Enable swap.
- Deploy microk8s from the 1.21 channel (`sudo snap install microk8s --classic --channel=1.21`) as we have a few memory optimizations on that channel.
- Disable HA, `microk8s disable ha-cluster`
- Use the `--runtime-config`, `--disable-admission-plugins` and `--feature-gates` to disable parts of the API server you do not need, see [1].

[1] https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/

**Comment by SuperJMN** [comment]
Thanks Konstantinos! I'll try to make it work by configuring it as mentioned. 
All the steps are more or less clear except for the latest. I'm a newbie and I wouldn't know what to disable. I'll try the first 3 points to see if it helps.

I hope somebody that has successfully configured MicroK8s for the Pi3 comes with a valid configuration.

**Comment by SuperJMN** [comment]
Getting this on MicroK8s 1.12:

```bash
pi@raspberrypi:~ $ microk8s disable ha-cluster

Traceback (most recent call last):
  File "/snap/microk8s/2215/scripts/wrappers/disable.py", line 43, in <module>
    disable(prog_name="microk8s disable")
  File "/snap/microk8s/2215/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/snap/microk8s/2215/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/snap/microk8s/2215/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/microk8s/2215/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/snap/microk8s/2215/scripts/wrappers/disable.py", line 36, in disable
    _, disabled_addons = get_status(get_available_addons(get_current_arch()), True)
  File "/snap/microk8s/2215/scripts/wrappers/status.py", line 157, in get_status
    kube_output = kubectl_get("all")
  File "/snap/microk8s/2215/scripts/wrappers/common/utils.py", line 169, in kubectl_get
    return run("kubectl", kubeconfig, "get", cmd, "--all-namespaces", die=False)
  File "/snap/microk8s/2215/scripts/wrappers/common/utils.py", line 39, in run
    result.check_returncode()
  File "/snap/microk8s/2215/usr/lib/python3.6/subprocess.py", line 389, in check_returncode
    self.stderr)
subprocess.CalledProcessError: Command '('kubectl', '--kubeconfig=/var/snap/microk8s/2215/credentials/client.config', 'get', 'all', '--all-namespaces')' returned non-zero exit status 1.
```
