### ISSUE TITLE
unable to run dashboard-proxy

### ISSUE THREAD

**Issue by Zyzto** [canonical/microk8s#2338]
I've installed microk8s on manjaro using snap and everything defaults runs except I can't expose the dashboard
which I run microk8s.dashboard-proxy I get this output
```
Checking if Dashboard is running.
Dashboard will be available at https://127.0.0.1:10443
Use the following token to login: <Token too Long to List> 
16:36:05.420633  700743 http.go:473] Error reading backend response: unexpected EOF
error: error upgrading connection: error sending request: Post "https://127.0.0.1:16443/api/v1/namespaces/kube-system/pods/kubernetes-dashboard-7ffd448895-vkcwb/portforward": unexpected EOF
Traceback (most recent call last):
  File "/snap/microk8s/2213/scripts/wrappers/dashboard-proxy.py", line 80, in <module>
    dashboard_proxy()
  File "/snap/microk8s/2213/scripts/wrappers/dashboard-proxy.py", line 74, in dashboard_proxy
    check_output(command)
  File "/snap/microk8s/2213/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/snap/microk8s/2213/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/snap/microk8s/current/microk8s-kubectl.wrapper', 'port-forward', '-n', 'kube-system', 'service/kubernetes-dashboard', '10443:443', '--address', '0.0.0.0']' returned non-zero exit status 1

```

[inspection-report-20210614_163635.tar.gz](https://github.com/ubuntu/microk8s/files/6648671/inspection-report-20210614_163635.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @Zyzto I see that the API server is not running. Here is what is failing with:
```
يونيو 14 16:36:05 ziadlaptop microk8s.daemon-apiserver[699845]: /snap/microk8s/2213/kube-apiserver: symbol lookup error: /snap/core/current/lib/x86_64-linux-gnu/libnss_dns.so.2: undefined symbol: __res_maybe_init, version GLIBC_PRIVATE
يونيو 14 16:36:05 ziadlaptop systemd[1]: snap.microk8s.daemon-apiserver.service: Main process exited, code=exited, status=127/n/a
```

There a re a few pages on the web about this problem but nothing recent.
