### ISSUE TITLE
Error: start node: raft_start():

### ISSUE THREAD

**Issue by luclu** [canonical/microk8s#2394]
```
 FAIL:  Service snap.microk8s.daemon-kubelite is not running
```
[inspection-report-20210630_215201.tar.gz](https://github.com/ubuntu/microk8s/files/6744210/inspection-report-20210630_215201.tar.gz)

```
Jun 30 20:59:22 k8s2 microk8s.daemon-kubelite[636093]: Starting kubelite
Jun 30 20:59:22 k8s2 microk8s.daemon-kubelite[636093]: I0630 20:59:22.713534  636093 daemon.go:73] Waiting for the API server
Jun 30 20:59:22 k8s2 microk8s.daemon-kubelite[636093]: I0630 20:59:22.717240  636093 daemon.go:65] Starting API Server
Jun 30 20:59:22 k8s2 microk8s.daemon-kubelite[636093]: Flag --insecure-port has been deprecated, This flag has no effect now and will be removed in v1.24.
Jun 30 20:59:22 k8s2 microk8s.daemon-kubelite[636093]: I0630 20:59:22.717822  636093 server.go:654] external host was not specified, using 10.20.0.82
Jun 30 20:59:22 k8s2 microk8s.daemon-kubelite[636093]: W0630 20:59:22.717913  636093 authentication.go:507] AnonymousAuth is not allowed with the AlwaysAllow authorizer. Resetting AnonymousAuth to false. You should use a different authorizer
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]: Error: start node: raft_start():
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]: F0630 20:59:23.256222  636093 daemon.go:67] API Server exited start node: raft_start():
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]: goroutine 147 [running]:
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0xc000010001, 0xc000e1c1c0, 0x59, 0x1b9)
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1021 +0xb9
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output(0x97ff6a0, 0xc000000003, 0x0, 0x0, 0xc000d20e00, 0x7cc2ba9, 0x9, 0x43, 0x0)
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:970 +0x191
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printf(0x97ff6a0, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x5f1e73a, 0x14, 0xc00038bec0, 0x1, ...)
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:751 +0x191
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.Fatalf(...)
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1509
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]: k8s.io/kubernetes/cmd/kubelite/app/daemons.StartAPIServer(0xc000606a00, 0x19, 0x20, 0xc0005555c0)
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubelite/app/daemons/daemon.go:67 +0x225
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]: created by k8s.io/kubernetes/cmd/kubelite/app.glob..func1
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubelite/app/server.go:42 +0x177
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]: goroutine 1 [select]:
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.WaitFor(0xc000576c90, 0xc000f9fc08, 0xc00007c4e0, 0x0, 0x0)
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:539 +0xf1
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.pollInternal(0xc000576c90, 0xc000f9fc08, 0x0, 0x0)
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:427 +0x87
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.pollImmediateInternal(0xc000576c90, 0xc000f9fc08, 0xc000576c90, 0x44f)
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:452 +0x74
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.PollImmediate(0x3b9aca00, 0x53d1ac1000, 0xc000f9fc08, 0x0, 0x0)
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:441 +0x4d
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]: k8s.io/kubernetes/vendor/k8s.io/controller-manager/app.WaitForAPIServer(0x6a3de28, 0xc00069f600, 0x53d1ac1000, 0x0, 0xc00068d680)
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/controller-manager/app/helper.go:35 +0x98
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]: k8s.io/kubernetes/cmd/kubelite/app/daemons.WaitForAPIServer(0x7fff3e324b11, 0x31, 0x53d1ac1000)
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubelite/app/daemons/daemon.go:83 +0x2cc
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]: k8s.io/kubernetes/cmd/kubelite/app.glob..func1(0x96da120, 0xc000a82f50, 0x0, 0x7)
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubelite/app/server.go:43 +0x1a5
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]: k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0x96da120, 0xc000070090, 0x7, 0x7, 0x96da120, 0xc000070090)
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:854 +0x2c2
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]: k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x96da120, 0x10, 0xc000000300, 0x7ca6ca)
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:958 +0x375
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]: k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:895
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]: k8s.io/kubernetes/cmd/kubelite/app.Execute()
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubelite/app/server.go:63 +0x31
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]: main.main()
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]:         _output/local/go/src/k8s.io/kubernetes/cmd/kubelite/kubelite.go:26 +0x111
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]: goroutine 6 [chan receive]:
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x97ff6a0)
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1164 +0x8b
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]: created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:418 +0xdf
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]: goroutine 110 [select]:
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]: k8s.io/kubernetes/vendor/go.opencensus.io/stats/view.(*worker).start(0xc00039ea50)
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/go.opencensus.io/stats/view/worker.go:154 +0xcd
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]: created by k8s.io/kubernetes/vendor/go.opencensus.io/stats/view.init.0
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/go.opencensus.io/stats/view/worker.go:32 +0x57
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]: goroutine 146 [chan receive]:
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.SetupSignalContext.func1(0xc0006b8a30)
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/signal.go:48 +0x36
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]: created by k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.SetupSignalContext
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/signal.go:47 +0xf3
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]: goroutine 138 [select]:
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x614c718, 0x692c7c0, 0xc000e79e30, 0x1, 0xc00007c120)
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:167 +0x118
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x614c718, 0x12a05f200, 0x0, 0x1, 0xc00007c120)
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Forever(0x614c718, 0x12a05f200)
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:81 +0x4f
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]: created by k8s.io/kubernetes/vendor/k8s.io/component-base/logs.InitLogs
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/component-base/logs/logs.go:58 +0x8a
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]: goroutine 140 [syscall]:
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]: os/signal.signal_recv(0x0)
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]:         /snap/go/7360/src/runtime/sigqueue.go:168 +0xa5
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]: os/signal.loop()
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]:         /snap/go/7360/src/os/signal/signal_unix.go:23 +0x25
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]: created by os/signal.Notify.func1.1
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]:         /snap/go/7360/src/os/signal/signal.go:151 +0x45
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]: goroutine 26 [select]:
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.poller.func1.1(0xc00007c6c0, 0x3b9aca00, 0x53d1ac1000, 0xc00007c600)
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:588 +0x135
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]: created by k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.poller.func1
Jun 30 20:59:23 k8s2 microk8s.daemon-kubelite[636093]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:571 +0x8c
Jun 30 20:59:23 k8s2 systemd[1]: snap.microk8s.daemon-kubelite.service: Main process exited, code=exited, status=255/EXCEPTION
Jun 30 20:59:23 k8s2 systemd[1]: snap.microk8s.daemon-kubelite.service: Failed with result 'exit-code'.
```

**Comment by ktsakalozos** [comment]
@MathieuBordere, I see this error coming from [1] how can I dig more into this? Thank you.

[1] https://github.com/canonical/go-dqlite/blob/master/app/app.go#L176

**Comment by MathieuBordere** [comment]
There is no comprehensive error message, let me check the code paths in raft that don't generate an error message. Meanwhile, @luclu can you paste the results of `ls -alh /var/snap/microk8s/current/var/kubenetes/backend` please?

**Comment by luclu** [comment]
@marcobellaccini 
```
total 463M
drwxrwxr-x 2 root microk8s 4.0K Jun 30 21:05 .
drwxr-xr-x 4 root root     4.0K Jun 15 19:41 ..
-rw-rw---- 1 root microk8s 7.4M Jun 29 20:06 0000000134386565-0000000134386871
-rw-rw---- 1 root microk8s 2.5M Jun 29 20:12 0000000134386872-0000000134386972
-rw-rw---- 1 root microk8s 4.5M Jun 29 20:24 0000000134386973-0000000134387157
-rw-rw---- 1 root microk8s 2.7M Jun 29 20:31 0000000134387158-0000000134387272
-rw-rw---- 1 root microk8s 3.0M Jun 29 20:40 0000000134387273-0000000134387393
-rw-rw---- 1 root microk8s 8.0M Jun 29 21:01 0000000134387394-0000000134387757
-rw-rw---- 1 root microk8s 3.7M Jun 29 21:09 0000000134387758-0000000134387916
-rw-rw---- 1 root microk8s 3.1M Jun 29 21:15 0000000134387917-0000000134388037
-rw-rw---- 1 root microk8s 3.8M Jun 29 21:22 0000000134388038-0000000134388199
-rw-rw---- 1 root microk8s 2.0M Jun 29 21:26 0000000134388200-0000000134388284
-rw-rw---- 1 root microk8s 5.1M Jun 29 21:34 0000000134388285-0000000134388509
-rw-rw---- 1 root microk8s  41K Jun 29 21:34 0000000134388510-0000000134388511
-rw-rw---- 1 root microk8s  29K Jun 29 21:35 0000000134388512-0000000134388512
-rw-rw---- 1 root microk8s 3.6M Jun 29 21:40 0000000134388513-0000000134388697
-rw-rw---- 1 root microk8s 2.1M Jun 29 21:43 0000000134388698-0000000134388782
-rw-rw---- 1 root microk8s 8.0M Jun 29 21:50 0000000134388783-0000000134389124
-rw-rw---- 1 root microk8s 5.5M Jun 29 21:54 0000000134389125-0000000134389416
-rw-rw---- 1 root microk8s 2.2K Jun 15 19:41 cluster.crt
-rw-rw---- 1 root microk8s 3.2K Jun 15 19:41 cluster.key
-rw-rw---- 1 root microk8s   64 Jun 30 21:06 cluster.yaml
-rw-rw-r-- 1 root microk8s    2 Jun 30 20:59 failure-domain
-rw-rw---- 1 root microk8s   58 Jun 15 19:41 info.yaml
srw-rw---- 1 root microk8s    0 Jun 30 21:05 kine.sock
-rw-rw---- 1 root microk8s   64 Jun 15 19:41 localnode.yaml
-rw-rw---- 1 root microk8s   32 Jun 29 21:35 metadata1
-rw-rw---- 1 root microk8s   32 Jun 29 21:35 metadata2
-rw-rw---- 1 root microk8s 8.0M Jun 30 21:06 open-1
-rw-rw---- 1 root microk8s 8.0M Jun 30 21:05 open-2
-rw-rw---- 1 root microk8s 8.0M Jun 30 21:05 open-3
-rw-rw---- 1 root microk8s 187M Jun 29 20:58 snapshot-10103-134387684-4363836
-rw-rw---- 1 root microk8s  120 Jun 29 20:58 snapshot-10103-134387684-4363836.meta
-rw-rw---- 1 root microk8s 188M Jun 29 21:41 snapshot-10114-134388708-6940018
-rw-rw---- 1 root microk8s   96 Jun 29 21:41 snapshot-10114-134388708-6940018.meta
```

**Comment by MathieuBordere** [comment]
can you do an `lz4 -t snapshot-10103-134387684-4363836` and `lz4 -t snapshot-10114-134388708-6940018` ?

If your data is not sensitive, you can send me a tarball of that folder at mathieu.bordere@canonical.com so I can do some checks on the data.

**Comment by marcobellaccini** [comment]
> @marcobellaccini 
> ```
> total 463M
> drwxrwxr-x 2 root microk8s 4.0K Jun 30 21:05 .
> drwxr-xr-x 4 root root     4.0K Jun 15 19:41 ..
> -rw-rw---- 1 root microk8s 7.4M Jun 29 20:06 0000000134386565-0000000134386871
> -rw-rw---- 1 root microk8s 2.5M Jun 29 20:12 0000000134386872-0000000134386972
> -rw-rw---- 1 root microk8s 4.5M Jun 29 20:24 0000000134386973-0000000134387157
> -rw-rw---- 1 root microk8s 2.7M Jun 29 20:31 0000000134387158-0000000134387272
> -rw-rw---- 1 root microk8s 3.0M Jun 29 20:40 0000000134387273-0000000134387393
> -rw-rw---- 1 root microk8s 8.0M Jun 29 21:01 0000000134387394-0000000134387757
> -rw-rw---- 1 root microk8s 3.7M Jun 29 21:09 0000000134387758-0000000134387916
> -rw-rw---- 1 root microk8s 3.1M Jun 29 21:15 0000000134387917-0000000134388037
> -rw-rw---- 1 root microk8s 3.8M Jun 29 21:22 0000000134388038-0000000134388199
> -rw-rw---- 1 root microk8s 2.0M Jun 29 21:26 0000000134388200-0000000134388284
> -rw-rw---- 1 root microk8s 5.1M Jun 29 21:34 0000000134388285-0000000134388509
> -rw-rw---- 1 root microk8s  41K Jun 29 21:34 0000000134388510-0000000134388511
> -rw-rw---- 1 root microk8s  29K Jun 29 21:35 0000000134388512-0000000134388512
> -rw-rw---- 1 root microk8s 3.6M Jun 29 21:40 0000000134388513-0000000134388697
> -rw-rw---- 1 root microk8s 2.1M Jun 29 21:43 0000000134388698-0000000134388782
> -rw-rw---- 1 root microk8s 8.0M Jun 29 21:50 0000000134388783-0000000134389124
> -rw-rw---- 1 root microk8s 5.5M Jun 29 21:54 0000000134389125-0000000134389416
> -rw-rw---- 1 root microk8s 2.2K Jun 15 19:41 cluster.crt
> -rw-rw---- 1 root microk8s 3.2K Jun 15 19:41 cluster.key
> -rw-rw---- 1 root microk8s   64 Jun 30 21:06 cluster.yaml
> -rw-rw-r-- 1 root microk8s    2 Jun 30 20:59 failure-domain
> -rw-rw---- 1 root microk8s   58 Jun 15 19:41 info.yaml
> srw-rw---- 1 root microk8s    0 Jun 30 21:05 kine.sock
> -rw-rw---- 1 root microk8s   64 Jun 15 19:41 localnode.yaml
> -rw-rw---- 1 root microk8s   32 Jun 29 21:35 metadata1
> -rw-rw---- 1 root microk8s   32 Jun 29 21:35 metadata2
> -rw-rw---- 1 root microk8s 8.0M Jun 30 21:06 open-1
> -rw-rw---- 1 root microk8s 8.0M Jun 30 21:05 open-2
> -rw-rw---- 1 root microk8s 8.0M Jun 30 21:05 open-3
> -rw-rw---- 1 root microk8s 187M Jun 29 20:58 snapshot-10103-134387684-4363836
> -rw-rw---- 1 root microk8s  120 Jun 29 20:58 snapshot-10103-134387684-4363836.meta
> -rw-rw---- 1 root microk8s 188M Jun 29 21:41 snapshot-10114-134388708-6940018
> -rw-rw---- 1 root microk8s   96 Jun 29 21:41 snapshot-10114-134388708-6940018.meta
> ```

What?

**Comment by MathieuBordere** [comment]
@luclu Thanks for sending me the data, the data looks OK, it loads fine on my machine & raft_start() exits successfully.
Let me look deeper what could be going wrong, your database is quite large, +- 1GB maybe it's related to that.

**Comment by MathieuBordere** [comment]
@luclu Do you have some background on when/under which circumstances the issue started?

**Comment by luclu** [comment]
Thank you @marcobellaccini 

Just some background: After updating from 1.19 to 1.21 and also upgrading the rook-operator afterwards some days later the cluster became very unstable. Some pods would crash suddenly and not come up until I manually delete it. Soon after some nodes (total 3 nodes, all master) could access the API eventually I tried to leave and readd them after purging and reinstalling microk8s one after another. This worked, but the cluster became very sluggish with random API timeouts. 

At this time Kasten.io had issues creating PVE snapshots (via rook-ceph) and left dozens of broken snapshot pods behind.
While trying to remove these pods and wind down the kasten helm chart I got more timeouts.

Thus I tried to remove the two API-timeouting nodes. 
Eventually I ended up here and now - with the last node not being able to start.

**Comment by MathieuBordere** [comment]
@ktsakalozos Could we try to recreate @luclu his environment? Honestly, for me, this is a bit over my head, I don't know a lot about k8s. The other option would be to provide some debug snaps to @luclu, to see which step fails.

**Comment by luclu** [comment]
@MathieuBordere Happy to run debug snaps!

**Comment by ktsakalozos** [comment]
I am also in favor of the debug snaps since even if we replicate the infrastructure we may not get the workload right.

@MathieuBordere some time ago in a similar situation we used a debug branch [1]. Would this branch be any good for this case? 

[1] https://github.com/MathieuBordere/raft/tree/debug-microk8s

**Comment by ktsakalozos** [comment]
Hi @luclu just creates a temporary debug branch that I would like you to switch to with:
```
sudo snap refreash microk8s --channel=1.21/stable/debug-2394
```

This branch will be available for about a month and your deployment should switch to `1.21/stable` automatically afterwards.

**Comment by luclu** [comment]
@ktsakalozos eventually I noticed that only 2GB of memory (ballooning was set to max to 16GB) was sliced for the VM running Ubuntu. Disabling the memory ballooning and giving the VM 16GB made microk8s start successfully.

Still the installation is incredibly slow and timing out on pretty much ever command - this is without HA enabled.

Do you still want me to run the debug snap (with only 2GB or 16GB) or do you consider this another issue and close this one?
