### ISSUE TITLE
`status` and `kubectl` sporadically become unresponsive

### ISSUE THREAD

**Issue by YoshikiTakashima** [canonical/microk8s#2406]
Hello.

I've got a cluster up, but I'm experiencing sporadic "outages" where `status` and `kubectl` claim that "microk8s is not running."

After some time, the cluster recovers. It also feels like it recovers after runing `inspect`, but I am not exactly sure.

Since I am not familiar with microk8s, I am looking for some help in interpreting the logs. Below is the inspect tarball right after the "outage."

[inspection-report-20210704_211708.tar.gz](https://github.com/ubuntu/microk8s/files/6766225/inspection-report-20210704_211708.tar.gz)

Thank you.

**Comment by balchua** [comment]
The scheduler or controller manager fails to elect a leader as shown in the logs.

```
Jul 04 20:24:32 mk8s microk8s.daemon-kubelite[1104878]: E0704 20:24:32.286762 1104878 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http: Handler timeout"}: http: Handler timeout
Jul 04 20:24:32 mk8s microk8s.daemon-kubelite[1104878]: E0704 20:24:32.287786 1104878 writers.go:130] apiserver was unable to write a fallback JSON response: http: Handler timeout
Jul 04 20:24:32 mk8s microk8s.daemon-kubelite[1104878]: I0704 20:24:32.301613 1104878 trace.go:205] Trace[1054552885]: "Update" url:/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/mk8s,user-agent:kubelite/v1.21.1 (linux/amd64) kubernetes/ba11848,client:127.0.0.1,accept:application/vnd.kubernetes.protobuf,application/json,protocol:HTTP/2.0 (04-Jul-2021 20:24:22.294) (total time: 10006ms):
Jul 04 20:24:32 mk8s microk8s.daemon-kubelite[1104878]: Trace[1054552885]: [10.006921944s] [10.006921944s] END
Jul 04 20:24:33 mk8s microk8s.daemon-kubelite[1104878]: E0704 20:24:33.192275 1104878 leaderelection.go:361] Failed to update lock: Put "https://127.0.0.1:16443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/kube-scheduler?timeout=15s": context deadline exceeded
Jul 04 20:24:33 mk8s microk8s.daemon-kubelite[1104878]: I0704 20:24:33.192384 1104878 leaderelection.go:278] failed to renew lease kube-system/kube-scheduler: timed out waiting for the condition
Jul 04 20:24:33 mk8s microk8s.daemon-kubelite[1104878]: F0704 20:24:33.192416 1104878 server.go:205] leaderelection lost
Jul 04 20:24:33 mk8s microk8s.daemon-kubelite[1104878]: goroutine 4981 [running]:
Jul 04 20:24:33 mk8s microk8s.daemon-kubelite[1104878]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0xc000010001, 0xc011e2f2c0, 0x41, 0x124)
Jul 04 20:24:33 mk8s microk8s.daemon-kubelite[1104878]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1021 +0xb9
```
When the scheduler or controller manager is unable to elect a leader, it will tip over kubelite and bring down the apiserver with it.

This is in my opinion a symptom of the backend getting slow response.

@ktsakalozos do you think the slow down coincides when kine performs compaction?  I don't have proof here though.  Looking at the logs, it seems that it can acquire the `lease`. But only on certain occassions where it find it too slow.

**Comment by ArseniiPetrovich** [comment]
Having the same issue. Some nodes are just going down from time to time. Is there a known way of troubleshooting this?

Seen the following in the logs:
```
Jul 06 13:30:42 two microk8s.daemon-kubelite[2340737]: E0706 13:30:42.019434 2340737 kubelet_node_status.go:470] "Error updating node status, will retry" err="failed to patch status \"{\\\"status\\\":{\\\"$setElementOrder/conditions\\\":[{\\
\"type\\\":\\\"NetworkUnavailable\\\"},{\\\"type\\\":\\\"MemoryPressure\\\"},{\\\"type\\\":\\\"DiskPressure\\\"},{\\\"type\\\":\\\"PIDPressure\\\"},{\\\"type\\\":\\\"Ready\\\"}],\\\"conditions\\\":[{\\\"lastHeartbeatTime\\\":\\\"2021-07-06T1
3:30:32Z\\\",\\\"lastTransitionTime\\\":\\\"2021-07-06T13:30:32Z\\\",\\\"message\\\":\\\"kubelet has sufficient memory available\\\",\\\"reason\\\":\\\"KubeletHasSufficientMemory\\\",\\\"status\\\":\\\"False\\\",\\\"type\\\":\\\"MemoryPressu
re\\\"},{\\\"lastHeartbeatTime\\\":\\\"2021-07-06T13:30:32Z\\\",\\\"lastTransitionTime\\\":\\\"2021-07-06T13:30:32Z\\\",\\\"message\\\":\\\"kubelet has no disk pressure\\\",\\\"reason\\\":\\\"KubeletHasNoDiskPressure\\\",\\\"status\\\":\\\"F
alse\\\",\\\"type\\\":\\\"DiskPressure\\\"},{\\\"lastHeartbeatTime\\\":\\\"2021-07-06T13:30:32Z\\\",\\\"lastTransitionTime\\\":\\\"2021-07-06T13:30:32Z\\\",\\\"message\\\":\\\"kubelet has sufficient PID available\\\",\\\"reason\\\":\\\"Kubel
etHasSufficientPID\\\",\\\"status\\\":\\\"False\\\",\\\"type\\\":\\\"PIDPressure\\\"},{\\\"lastHeartbeatTime\\\":\\\"2021-07-06T13:30:32Z\\\",\\\"lastTransitionTime\\\":\\\"2021-07-06T13:30:32Z\\\",\\\"message\\\":\\\"kubelet is posting read
y status. AppArmor enabled\\\",\\\"reason\\\":\\\"KubeletReady\\\",\\\"status\\\":\\\"True\\\",\\\"type\\\":\\\"Ready\\\"}]}}\" for node \"two\": Patch \"https://127.0.0.1:16443/api/v1/nodes/two/status?timeout=10s\": read tcp 127.0.0.1:60664
->127.0.0.1:16443: use of closed network connection"


```

**Comment by ArseniiPetrovich** [comment]
Attaching my tarball as well [inspection-report-20210706_133003.tar.gz](https://github.com/ubuntu/microk8s/files/6770408/inspection-report-20210706_133003.tar.gz)
