### ISSUE TITLE
Apiserver timeout on some write operations

### ISSUE THREAD

**Issue by matlad** [canonical/microk8s#2413]
I have strange behavior when a edit configuration like
kubectl edit deployment test
it pass and when a reed it i get modified version.
But it looks that  kube-scheduler and kube-controller-manager keep restarting because timeout of coordination.Lease update

kube-controller-manager
```
Jul 08 08:11:12 k8s-1 microk8s.daemon-controller-manager[3010975]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1026 +0xb9
Jul 08 08:11:12 k8s-1 microk8s.daemon-controller-manager[3010975]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0xc00000e001, 0xc000f12540, 0x4c, 0xde)
Jul 08 08:11:12 k8s-1 microk8s.daemon-controller-manager[3010975]: goroutine 1 [running]:
Jul 08 08:11:12 k8s-1 microk8s.daemon-controller-manager[3010975]: F0708 08:11:12.215158 3010975 controllermanager.go:294] leaderelection lost
Jul 08 08:11:12 k8s-1 microk8s.daemon-controller-manager[3010975]: I0708 08:11:12.215139 3010975 leaderelection.go:278] failed to renew lease kube-system/kube-controller-manager: timed out waiting for the condition
Jul 08 08:11:12 k8s-1 microk8s.daemon-controller-manager[3010975]: E0708 08:11:12.215103 3010975 leaderelection.go:325] error retrieving resource lock kube-system/kube-controller-manager: Get "https://127.0.0.1:16443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/kube-controller-manager?timeout=30s": context deadline exceeded
Jul 08 08:11:08 k8s-1 microk8s.daemon-controller-manager[3010975]: I0708 08:11:08.639246 3010975 shared_informer.go:240] Waiting for caches to sync for endpoint_slice_mirroring
Jul 08 08:11:08 k8s-1 microk8s.daemon-controller-manager[3010975]: I0708 08:11:08.639235 3010975 endpointslicemirroring_controller.go:211] Starting EndpointSliceMirroring controller
Jul 08 08:11:08 k8s-1 microk8s.daemon-controller-manager[3010975]: I0708 08:11:08.639167 3010975 controllermanager.go:554] Started "endpointslicemirroring"
Jul 08 08:11:02 k8s-1 microk8s.daemon-controller-manager[3010975]: E0708 08:11:02.758423 3010975 leaderelection.go:361] Failed to update lock: Operation cannot be fulfilled on leases.coordination.k8s.io "kube-controller-manager": the object has been modified; please apply your changes to the latest version and try again
Jul 08 08:10:58 k8s-1 microk8s.daemon-controller-manager[3010975]: I0708 08:10:58.426503 3010975 shared_informer.go:247] Caches are synced for tokens
Jul 08 08:10:58 k8s-1 microk8s.daemon-controller-manager[3010975]: I0708 08:10:58.326327 3010975 shared_informer.go:240] Waiting for caches to sync for tokens
Jul 08 08:10:58 k8s-1 microk8s.daemon-controller-manager[3010975]: E0708 08:10:58.325825 3010975 controllermanager.go:446] unable to get all supported resources from server: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
Jul 08 08:10:55 k8s-1 microk8s.daemon-controller-manager[3010975]: I0708 08:10:55.675517 3010975 request.go:655] Throttling request took 1.048797233s, request: GET:https://127.0.0.1:16443/apis/admissionregistration.k8s.io/v1beta1?timeout=32s
Jul 08 08:10:42 k8s-1 microk8s.daemon-controller-manager[3010975]: I0708 08:10:42.215052 3010975 event.go:291] "Event occurred" object="kube-system/kube-controller-manager" kind="Lease" apiVersion="coordination.k8s.io/v1" type="Normal" reason="LeaderElection" message="k8s-1_453cb8e9-5114-49cd-ba8f-18d7593430c0 became leader"
Jul 08 08:10:42 k8s-1 microk8s.daemon-controller-manager[3010975]: I0708 08:10:42.214881 3010975 leaderelection.go:253] successfully acquired lease kube-system/kube-controller-manager
Jul 08 08:09:27 k8s-1 microk8s.daemon-controller-manager[3010975]: E0708 08:09:27.993594 3010975 leaderelection.go:361] Failed to update lock: Operation cannot be fulfilled on leases.coordination.k8s.io "kube-controller-manager": the object has been modified; please apply your changes to the latest version and try again
Jul 08 08:07:25 k8s-1 microk8s.daemon-controller-manager[3010975]: E0708 08:07:25.965223 3010975 leaderelection.go:361] Failed to update lock: Operation cannot be fulfilled on leases.coordination.k8s.io "kube-controller-manager": the object has been modified; please apply your changes to the latest version and try again
Jul 08 08:07:00 k8s-1 microk8s.daemon-controller-manager[3010975]: E0708 08:07:00.360956 3010975 leaderelection.go:361] Failed to update lock: Put "https://127.0.0.1:16443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/kube-controller-manager?timeout=30s": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Jul 08 08:05:39 k8s-1 microk8s.daemon-controller-manager[3010975]: E0708 08:05:39.145377 3010975 leaderelection.go:325] error retrieving resource lock kube-system/kube-controller-manager: Get "https://127.0.0.1:16443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/kube-controller-manager?timeout=30s": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Jul 08 08:03:01 k8s-1 microk8s.daemon-controller-manager[3010975]: I0708 08:03:01.506620 3010975 leaderelection.go:243] attempting to acquire leader lease kube-system/kube-controller-manager...

```
apiserver
```
Jul 08 08:10:02 k8s-1 microk8s.daemon-apiserver[2967536]: I0708 08:10:02.064472 2967536 trace.go:205] Trace[562566019]: "Get" url:/apis/flowcontrol.apiserver.k8s.io/v1beta1/prioritylevelconfigurations/catch-all,user-agent:kube-apiserver/v1.20.7 (linux/amd64) kubernetes/df7df22,client:::1 (08-Jul-2021 08:10:00.426) (total time: 1638ms):
Jul 08 08:10:01 k8s-1 microk8s.daemon-apiserver[2967536]: Trace[567827926]: [9.995077637s] [9.995077637s] END
Jul 08 08:10:01 k8s-1 microk8s.daemon-apiserver[2967536]: I0708 08:10:01.909248 2967536 trace.go:205] Trace[567827926]: "Update" url:/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/k8s-1,user-agent:kubelet/v1.20.7 (linux/amd64) kubernetes/df7df22,client:127.0.0.1 (08-Jul-2021 08:09:51.914) (total time: 9995ms):
Jul 08 08:10:01 k8s-1 microk8s.daemon-apiserver[2967536]: time="2021-07-08T08:10:01Z" level=error msg="error in txn: query (try: 0): context canceled"
Jul 08 08:10:01 k8s-1 microk8s.daemon-apiserver[2967536]: time="2021-07-08T08:10:01Z" level=error msg="error in txn: query (try: 0): context canceled"
Jul 08 08:10:01 k8s-1 microk8s.daemon-apiserver[2967536]: E0708 08:10:01.908995 2967536 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
Jul 08 08:10:01 k8s-1 microk8s.daemon-apiserver[2967536]: Trace[310010792]: [9.99472838s] [9.99472838s] END
Jul 08 08:10:01 k8s-1 microk8s.daemon-apiserver[2967536]: I0708 08:10:01.908971 2967536 trace.go:205] Trace[310010792]: "GuaranteedUpdate etcd3" type:*coordination.Lease (08-Jul-2021 08:09:51.914) (total time: 9994ms):
```

versions 
```
NAME    STATUS   ROLES    AGE   VERSION
k8s-3   Ready    <none>   72d   v1.20.6-34+e4abae43f6acde
k8s-2   Ready    <none>   72d   v1.20.7-34+df7df22a741dbc
k8s-1   Ready    <none>   72d   v1.20.7-34+df7df22a741dbc
```
Installated in LXD on Ubuntu 20.04 
  
[inspection-report-20210708_083746.tar.gz](https://github.com/ubuntu/microk8s/files/6783005/inspection-report-20210708_083746.tar.gz)

**Comment by joedborg** [comment]
Hey @matlad,

Out of interest, what specs did you give to your LXD VM?

**Comment by matlad** [comment]
#microk8s node
arch: amd64
features: fuse=1,nesting=1
hostname: k8s-1
memory: 61440
nameserver: 10.10.0.31
net0: name=vmbr1,bridge=vmbr1,gw=10.10.0.31,hwaddr=F6:37:7D:4A:BB:0A,ip=10.10.0.201/24,type=veth
onboot: 1
ostype: ubuntu
rootfs: local:301/vm-301-disk-0.raw,size=100G
swap: 0
tags: k8s
lxc.apparmor.profile: unconfined
lxc.cap.drop: 
lxc.mount.auto: proc:rw sys:rw
lxc.cgroup.devices.allow: a

**Comment by joedborg** [comment]
I've tried to reproduce this with the documentation (https://microk8s.io/docs/lxd), but can't trigger the timeouts.  Could you please try with 1.21/stable and see if the issue still persists?

Thanks,
Joe

**Comment by balchua** [comment]
Hi @joedborg i think the issue is similar to this.
https://github.com/ubuntu/microk8s/issues/2406. Which happens to be in 1.21/stable.

**Comment by matlad** [comment]
it seem that i have some issues also with calico
k -n kube-system logs calico-kube-controllers-5884db5c4c-8g45t calico-kube-controllers 
shows some permission issues
[calico-kube-controllers.log](https://github.com/ubuntu/microk8s/files/6790146/calico-kube-controllers.log)
