### ISSUE TITLE
Can't install Prometheus... throwing error that command does not work

### ISSUE THREAD

**Issue by FaresKi** [canonical/microk8s#2433]
I've freshly installed the latest version on the classic channel using the following command : 
`sudo snap install microk8s --classic`

This is my current config (EC2 instance on AWS) : 
```sh
ubuntu@ip-xxxx~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```
I tried finding out which 
ubuntu@ip-xxxx:~$ microk8s.status
microk8s is not running. Use microk8s inspect for a deeper inspection.
```sh
ubuntu@ip-xxxx:~$ microk8s inspect
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-kubelite is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
Inspecting juju
  Inspect Juju
Inspecting kubeflow
  Inspect Kubeflow

Building the report tarball
  Report tarball is at /var/snap/microk8s/2262/inspection-report-20210713_130831.tar.gz
```
But whenever you run the following command : `microk8s.enable dashboard prometheus`
and this happened : 
```sh
ubuntu@ip-xxxx:~$ microk8s.enable dashboard prometheus

Traceback (most recent call last):
  File "/snap/microk8s/2262/scripts/wrappers/enable.py", line 43, in <module>
    enable(prog_name="microk8s enable")
  File "/snap/microk8s/2262/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/snap/microk8s/2262/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/snap/microk8s/2262/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/microk8s/2262/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/snap/microk8s/2262/scripts/wrappers/enable.py", line 36, in enable
    enabled_addons, _ = get_status(get_available_addons(get_current_arch()), True)
  File "/snap/microk8s/2262/scripts/wrappers/status.py", line 157, in get_status
    kube_output = kubectl_get("all")
  File "/snap/microk8s/2262/scripts/wrappers/common/utils.py", line 169, in kubectl_get
    return run("kubectl", kubeconfig, "get", cmd, "--all-namespaces", die=False)
  File "/snap/microk8s/2262/scripts/wrappers/common/utils.py", line 39, in run
    result.check_returncode()
  File "/snap/microk8s/2262/usr/lib/python3.6/subprocess.py", line 389, in check_returncode
    self.stderr)
subprocess.CalledProcessError: Command '('kubectl', '--kubeconfig=/var/snap/microk8s/2262/credentials/client.config', 'get', 'all', '--all-namespaces')' returned non-zero exit status 1.
```
Could you tell me why?

**Comment by balchua** [comment]
Hi its likely that the apiserver is down or just taking time to start.

**Comment by FaresKi** [comment]
How would I start the apiserver if it's down?

**Comment by ktsakalozos** [comment]
> How would I start the apiserver if it's down?

With `microk8s start` you can start all services.

It would help us investigate this issue if you could attach the `microk8s inspect` tarball.

**Comment by FaresKi** [comment]
Ran the `microk8s start` command, no changes.
I added the tarball [here](https://github.com/ubuntu/microk8s/files/6856793/inspection-report-20210713_130831.tar.gz).
