### ISSUE TITLE
daemon-kubelite crashloop on 1.22

### ISSUE THREAD

**Issue by jpalpant** [canonical/microk8s#2531]
daemon-kubelite is unable to start the API server process on my single-node cluster. After a few minutes of waiting, it fails and crashloops. The following are the systemd logs that seem relevant:

<details>
<summary>daemon-kubelite systemd logs</summary>

```
Aug 18 11:06:23 ubuntu-node-01 microk8s.daemon-kubelite[183876]: Starting kubelite
Aug 18 11:06:23 ubuntu-node-01 microk8s.daemon-kubelite[183876]: I0818 11:06:23.950873  183876 daemon.go:73] Waiting for the API server
Aug 18 11:06:23 ubuntu-node-01 microk8s.daemon-kubelite[183876]: I0818 11:06:23.951295  183876 daemon.go:65] Starting API Server
Aug 18 11:06:23 ubuntu-node-01 microk8s.daemon-kubelite[183876]: Flag --insecure-port has been deprecated, This flag has no effect now and will be removed in v1.24.
Aug 18 11:06:23 ubuntu-node-01 microk8s.daemon-kubelite[183876]: I0818 11:06:23.951586  183876 server.go:591] external host was not specified, using 192.168.0.31
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: Error: context deadline exceeded
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: F0818 11:11:24.624965  183876 daemon.go:67] API Server exited context deadline exceeded
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: goroutine 144 [running]:
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0xc00013e001, 0xc000438780, 0x58, 0x9a)
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1026 +0xbb
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output(0x5573adf8a3e0, 0xc000000003, 0x0, 0x0, 0xc0003d8690, 0x0, 0x5573ac5b7725, 0x9, 0x43, 0x0)
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:975 +0x1e5
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printf(0x5573adf8a3e0, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x5573a92fd755, 0x14, 0xc00071ef60, 0x1, ...)
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:753 +0x19a
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.Fatalf(...)
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1514
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: k8s.io/kubernetes/cmd/kubelite/app/daemons.StartAPIServer(0xc000817a00, 0x19, 0x20, 0xc00007d200)
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubelite/app/daemons/daemon.go:67 +0x225
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: created by k8s.io/kubernetes/cmd/kubelite/app.glob..func1
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubelite/app/server.go:42 +0x177
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: goroutine 1 [select]:
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.WaitForWithContext(0x5573ab25e4e8, 0xc00013a010, 0xc0008e59b0, 0xc000238170, 0x0, 0x0)
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:655 +0x10b
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.poll(0x5573ab25e4e8, 0xc00013a010, 0xc0008e5901, 0xc0008e59b0, 0xc000238170, 0x5573aa80a4c0, 0xc000238170)
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:591 +0xa6
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.PollImmediateWithContext(0x5573ab25e4e8, 0xc00013a010, 0x3b9aca00, 0x53d1ac1000, 0xc000238170, 0x5573aa94ff40, 0x1)
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:523 +0x68
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.PollImmediate(0x3b9aca00, 0x53d1ac1000, 0xc00076c180, 0x0, 0x0)
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:509 +0x71
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: k8s.io/kubernetes/vendor/k8s.io/controller-manager/app.WaitForAPIServer(0x5573ab2ebb28, 0xc000c6f760, 0x53d1ac1000, 0x0, 0xc000c6db00)
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/controller-manager/app/helper.go:35 +0xa5
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: k8s.io/kubernetes/cmd/kubelite/app/daemons.WaitForAPIServer(0x7ffd8b93eb0d, 0x31, 0x53d1ac1000)
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubelite/app/daemons/daemon.go:83 +0x2cc
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: k8s.io/kubernetes/cmd/kubelite/app.glob..func1(0x5573ade98a20, 0xc0003d85b0, 0x0, 0x7)
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubelite/app/server.go:43 +0x1a5
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0x5573ade98a20, 0xc000142010, 0x7, 0x7, 0x5573ade98a20, 0xc000142010)
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:856 +0x2c2
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x5573ade98a20, 0x10, 0xc000000300, 0x5573a4f08d8c)
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:960 +0x375
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:897
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: k8s.io/kubernetes/cmd/kubelite/app.Execute()
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubelite/app/server.go:63 +0x33
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: main.main()
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         _output/local/go/src/k8s.io/kubernetes/cmd/kubelite/kubelite.go:26 +0x111
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: goroutine 19 [chan receive]:
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x5573adf8a3e0)
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1169 +0x8d
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:420 +0xdf
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: goroutine 130 [select]:
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: k8s.io/kubernetes/vendor/go.opencensus.io/stats/view.(*worker).start(0xc0000e69b0)
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/go.opencensus.io/stats/view/worker.go:154 +0xcf
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: created by k8s.io/kubernetes/vendor/go.opencensus.io/stats/view.init.0
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/go.opencensus.io/stats/view/worker.go:32 +0x59
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: goroutine 154 [sleep]:
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: time.Sleep(0x3b9aca00)
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /snap/go/7954/src/runtime/time.go:193 +0xd8
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: k8s.io/kubernetes/vendor/github.com/canonical/go-dqlite/internal/protocol.makeRetryStrategies.func1(0x12e, 0x12d)
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/canonical/go-dqlite/internal/protocol/connector.go:314 +0x67
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: k8s.io/kubernetes/vendor/github.com/Rican7/retry.shouldAttempt(0x12e, 0xc000011158, 0x1, 0x1, 0x5573adfbde01)
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/Rican7/retry/retry.go:32 +0x49
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: k8s.io/kubernetes/vendor/github.com/Rican7/retry.Retry(0xc0000bcd48, 0xc000011158, 0x1, 0x1, 0x1, 0x1)
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/Rican7/retry/retry.go:19 +0xa5
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: k8s.io/kubernetes/vendor/github.com/canonical/go-dqlite/internal/protocol.(*Connector).Connect(0xc0000bcdf8, 0x5573ab25e4b0, 0xc000cd3940, 0x7f19ffa04f60, 0x10, 0x10)
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/canonical/go-dqlite/internal/protocol/connector.go:73 +0xc9
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: k8s.io/kubernetes/vendor/github.com/canonical/go-dqlite/client.FindLeader(0x5573ab25e4b0, 0xc000cd3940, 0x5573ab1e4cc0, 0xc000cd38c0, 0xc0002ad9f0, 0x2, 0x2, 0x5802e1b8044, 0xc00108ac80, 0xc0008ff2c0)
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/canonical/go-dqlite/client/leader.go:26 +0x1ac
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: k8s.io/kubernetes/vendor/github.com/canonical/go-dqlite/app.(*App).Leader(0xc00082cf70, 0x5573ab25e4b0, 0xc000cd3940, 0x0, 0x2, 0xc0000b0701)
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/canonical/go-dqlite/app/app.go:403 +0x7e
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: k8s.io/kubernetes/vendor/github.com/canonical/go-dqlite/app.(*App).run(0xc00082cf70, 0x5573ab25e4b0, 0xc000cd3940, 0x6fc23ac00, 0x0)
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/canonical/go-dqlite/app/app.go:458 +0x165
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: created by k8s.io/kubernetes/vendor/github.com/canonical/go-dqlite/app.New
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/canonical/go-dqlite/app/app.go:238 +0x1013
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: goroutine 153 [IO wait, 5 minutes]:
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: internal/poll.runtime_pollWait(0x7f19d63e6070, 0x72, 0x0)
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /snap/go/7954/src/runtime/netpoll.go:222 +0x65
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: internal/poll.(*pollDesc).wait(0xc0005f5618, 0x72, 0x0, 0x0, 0x5573a92c880f)
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /snap/go/7954/src/internal/poll/fd_poll_runtime.go:87 +0x47
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: internal/poll.(*pollDesc).waitRead(...)
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /snap/go/7954/src/internal/poll/fd_poll_runtime.go:92
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: internal/poll.(*FD).Accept(0xc0005f5600, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /snap/go/7954/src/internal/poll/fd_unix.go:401 +0x212
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: net.(*netFD).accept(0xc0005f5600, 0xc00027bee0, 0x5573a489693a, 0x10)
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /snap/go/7954/src/net/fd_unix.go:172 +0x45
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: net.(*TCPListener).accept(0xc000633d70, 0x5573aa7f98c0, 0xc00024cb70, 0x5573ab1e1bb0)
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /snap/go/7954/src/net/tcpsock_posix.go:139 +0x34
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: net.(*TCPListener).Accept(0xc000633d70, 0xc00013a010, 0x5573ab25e4b0, 0xc000e90100, 0xc00024cb70)
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /snap/go/7954/src/net/tcpsock.go:261 +0x66
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: k8s.io/kubernetes/vendor/github.com/canonical/go-dqlite/app.(*App).proxy(0xc00082cf70)
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/canonical/go-dqlite/app/app.go:416 +0xa9
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: created by k8s.io/kubernetes/vendor/github.com/canonical/go-dqlite/app.New
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/canonical/go-dqlite/app/app.go:232 +0x1227
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: goroutine 140 [select]:
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x5573ab0e6d10, 0x5573ab1d9ae8, 0xc0000ffbc0, 0x1, 0xc00010e360)
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:167 +0x118
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x5573ab0e6d10, 0x12a05f200, 0x0, 0x1, 0xc00010e360)
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x9a
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Forever(0x5573ab0e6d10, 0x12a05f200)
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:81 +0x51
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: created by k8s.io/kubernetes/vendor/k8s.io/component-base/logs.InitLogs
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/component-base/logs/logs.go:58 +0x8c
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: goroutine 142 [syscall, 5 minutes]:
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: os/signal.signal_recv(0x0)
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /snap/go/7954/src/runtime/sigqueue.go:168 +0xa5
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: os/signal.loop()
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /snap/go/7954/src/os/signal/signal_unix.go:23 +0x25
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: created by os/signal.Notify.func1.1
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /snap/go/7954/src/os/signal/signal.go:151 +0x46
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: goroutine 143 [chan receive, 5 minutes]:
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.SetupSignalContext.func1(0xc000e012e0)
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/signal.go:48 +0x38
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: created by k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.SetupSignalContext
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/signal.go:47 +0xf9
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: goroutine 167 [select]:
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.poller.func1.1(0xc0008f00c0, 0x3b9aca00, 0x53d1ac1000, 0x5573ab25e4b0, 0xc000e900c0)
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:705 +0x157
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]: created by k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.poller.func1
Aug 18 11:11:24 ubuntu-node-01 microk8s.daemon-kubelite[183876]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:688 +0x98
Aug 18 11:11:24 ubuntu-node-01 systemd[1]: snap.microk8s.daemon-kubelite.service: Main process exited, code=exited, status=255/EXCEPTION
Aug 18 11:11:24 ubuntu-node-01 systemd[1]: snap.microk8s.daemon-kubelite.service: Failed with result 'exit-code'.
Aug 18 11:11:24 ubuntu-node-01 systemd[1]: snap.microk8s.daemon-kubelite.service: Scheduled restart job, restart counter is at 21.
Aug 18 11:11:24 ubuntu-node-01 systemd[1]: Stopped Service for snap application microk8s.daemon-kubelite.
Aug 18 11:11:24 ubuntu-node-01 systemd[1]: Started Service for snap application microk8s.daemon-kubelite.
```

</details>

I don't really understand this stack trace. I'm not entirely sure what caused this problem - it did not happen immediately after the upgrade to 1.22. I believe it began following the first restart after that upgrade. Is my cluster corrupted in some way?

`microk8s inspect` generally reports all services running, because the daemon-kubelite service is running most of the time (just crashlooping). Tarball attached:

[inspection-report-20210818_111820.tar.gz](https://github.com/ubuntu/microk8s/files/7009316/inspection-report-20210818_111820.tar.gz)

**Comment by balchua** [comment]
It looks like the file `/var/snap/microk8s/current/var/kubernetes/backend/cluster.yaml` is empty.

Can you check if it is?

**Comment by jpalpant** [comment]
It is indeed empty, as you expected

```
[palpantlab-sfo] Wed Aug 18 22:07:28 | justin@ubuntu-node-01:~
$ ls -larth /var/snap/microk8s/current/var/kubernetes/backend/cluster.yaml
-rw-rw---- 1 root microk8s 0 Aug 13 08:50 /var/snap/microk8s/current/var/kubernetes/backend/cluster.yaml
[palpantlab-sfo] Wed Aug 18 22:07:38 | justin@ubuntu-node-01:~
$ cat /var/snap/microk8s/current/var/kubernetes/backend/cluster.yaml
[palpantlab-sfo] Wed Aug 18 22:07:40 | justin@ubuntu-node-01:~
$ 
```

I happen to have a backup of this file from about two weeks ago which has this content:

```
- Address: 127.0.0.1:19001
  ID: 3297041220608546238
  Role: 0
```

I copied that old version in place of the empty one and my cluster starts up. Nice and easy fix, thank you!

I assume, though I don't remember doing this, that I messed up this file somehow. If there is any way it could have gotten corrupted during upgrade, I'm sure others will chime in here, but for now, this is probably resolved.

**Comment by balchua** [comment]
I know there is already a fix on this.  https://github.com/canonical/go-dqlite/pull/147

@ktsakalozos @mathieubordere
I think this is already in 1.22 but somehow it seems to happen.
