### ISSUE TITLE
Kubernetes pod running via MicrosK8s on Ubuntu OS on a GCE VM on google cloud is not able to access metadata service.

### ISSUE THREAD

**Issue by amit-chandak-unskript** [canonical/microk8s#2555]
I am running micro8ks 1.19 with dns, dashboard and storage enabled.

I am trying to run google cloud python sdk from inside a k8 pod, running on google compute engine. There is a service account attached to the VM, which is giving it access to the secrets manager. I am able to access secrets manager from the host, however running the python sdk from k8 pod complains of not able to access the metadata service

```
>>> secret_id = 'unskript_test'
>>> name = client.secret_path(project_id, secret_id)
>>> response = client.get_secret(request={"name": name})
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 67, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/opt/conda/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
    status = StatusCode.UNAVAILABLE
    details = "Getting metadata from plugin failed with error: Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Compute Engine Metadata server unavailable"
    debug_error_string = "{"created":"@1630634901.103779641","description":"Getting metadata from plugin failed with error: Failed to retrieve http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true from the Google Compute Enginemetadata service. Compute Engine Metadata server unavailable","file":"src/core/lib/security/credentials/plugin/plugin_credentials.cc","file_line":90,"grpc_status":14}"
>
```

metadata.google.internal doesnt get resolved from the k8 pod

```
jovyan@jovyan-25ca6c8c-157d-49e5-9366-f9d57fcb7a9f:~$ wget http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true
--2021-09-03 02:11:19--  http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true
Resolving metadata.google.internal (metadata.google.internal)... failed: Name or service not known.
wget: unable to resolve host address ‘metadata.google.internal’
```

However, host is able to resolve it

```
ubuntu@gcp-test-proxy:~$ wget http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true
--2021-09-03 02:11:27--  http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true
Resolving metadata.google.internal (metadata.google.internal)... 169.254.169.254
Connecting to metadata.google.internal (metadata.google.internal)|169.254.169.254|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2021-09-03 02:11:27 ERROR 403: Forbidden.
```

How can i make the pod resolve metadata.google.internal?

Seems like microk8ks specific DNS issue, as minikube in the same environment works fine.

**Comment by balchua** [comment]
Its likely that you may want to use the hosts' `/etc/resolv.conf`

I haven't tried this though, but i think you can do this when enabling the dns.
`microk8s enable dns:/etc/resolv.conf`

**Comment by amit-chandak-unskript** [comment]
> Its likely that you may want to use the hosts' `/etc/resolv.conf`
> 
> I haven't tried this though, but i think you can do this when enabling the dns.
> `microk8s enable dns:/etc/resolv.conf`

Thanks @balchua, i tried that, it didnt help.

This is the resolv.conf from one of the pods

```
ubuntu@unskript-proxy-5780ef6bbd25364c:~$ kubectl  exec -it kernel-image-puller-b8ccp -n eg  -- cat /etc/resolv.conf
search eg.svc.cluster.local svc.cluster.local cluster.local us-west1-a.c.unskript-dev.internal c.unskript-dev.internal google.internal
nameserver 10.152.183.10
options ndots:5
```

I also tried adding the following conf in the **coredns** configmap

```
hosts custom.hosts metadata.google.internal {
        169.254.169.254 metadata.google.internal
        fallthrough
}
```
but that didnt help as well.

**Comment by balchua** [comment]
How about changing the coredns configmap `forward 8.8.8.8` to `forward . /etc/resolv.conf` and then bounce the coredns pod.

**Comment by amit-chandak-unskript** [comment]
@balchua , that didnt help either, it caused a loop

```
ubuntu@unskript-proxy-5780ef6bbd25364c:~$ kubectl logs coredns-86f78bb79c-rvx4l -n kube-system
.:53
[INFO] plugin/reload: Running configuration MD5 = 9c84359c8241e872f3e8b219e786d4b7
CoreDNS-1.6.6
linux/amd64, go1.13.5, 6a7a75e
[FATAL] plugin/loop: Loop (127.0.0.1:39284 -> :53) detected for zone ".", see https://coredns.io/plugins/loop#troubleshooting. Query: "HINFO 8610968144556850859.2002956450959204032."
```

here is the coredns configmap

```
ubuntu@unskript-proxy-5780ef6bbd25364c:~$ kubectl describe configmap coredns -n kube-system
Name:         coredns
Namespace:    kube-system
Labels:       addonmanager.kubernetes.io/mode=EnsureExists
              k8s-app=kube-dns
Annotations:  <none>

Data
====
Corefile:
----
.:53 {
    errors
    health {
      lameduck 5s
    }
    ready
    log . {
      class error
    }
    kubernetes cluster.local in-addr.arpa ip6.arpa {
      pods insecure
      fallthrough in-addr.arpa ip6.arpa
    }
    prometheus :9153
    #forward . 8.8.8.8 8.8.4.4
    forward . /etc/resolv.conf
    cache 30
    loop
    reload
    loadbalance
}

Events:  <none>
```

**Comment by ktsakalozos** [comment]
Is it possible to use a HostAlias [1] so that your pod knows the IP of `metadata.google.internal` ?

[1] https://kubernetes.io/docs/tasks/network/customize-hosts-file-for-pods/

**Comment by amit-chandak-unskript** [comment]
> Is it possible to use a HostAlias [1] so that your pod knows the IP of `metadata.google.internal` ?
> 
> [1] https://kubernetes.io/docs/tasks/network/customize-hosts-file-for-pods/

Thanks @ktsakalozos , i will try it out and update here.

**Comment by amit-chandak-unskript** [comment]
Just an update, i ran into this issue on AWS EC2 instance as well. The pod was able to resolve only public DNS names, was not able to resolve dns names private to a particular vpc. 
I tried with replacing 8.8.8.8 with /etc/resolv.conf but that caused loop in the coredns as i mentioned earlier. 
I gave up on microk8s and moved to k3s.
