### ISSUE TITLE
Calico Node fails on Nvidia Jetson

### ISSUE THREAD

**Issue by joedborg** [canonical/microk8s#2581]
Fresh Nvidia Jetson fails to start Calico Node with the following error.

```
goroutine 110 [running]:
github.com/sirupsen/logrus.Entry.log(0x40000d8180, 0x4000574ab0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/pkg/mod/github.com/projectcalico/logrus@v1.0.4-calico/entry.go:128 +0x5d4
github.com/sirupsen/logrus.(*Entry).Panic(0x4000277770, 0x4000965bb8, 0x1, 0x1)
        /go/pkg/mod/github.com/projectcalico/logrus@v1.0.4-calico/entry.go:173 +0xb4
github.com/projectcalico/felix/ipsets.(*IPSets).ApplyUpdates(0x40005e0240)
        /go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20200311115901-aa0a22d97c2d/ipsets/ipsets.go:342 +0x2bc
github.com/projectcalico/felix/dataplane/linux.(*InternalDataplane).apply.func1(0x400051b400, 0x40002c0424, 0x40005e0240)
        /go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20200311115901-aa0a22d97c2d/dataplane/linux/int_dataplane.go:1290 +0x28
created by github.com/projectcalico/felix/dataplane/linux.(*InternalDataplane).apply
        /go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20200311115901-aa0a22d97c2d/dataplane/linux/int_dataplane.go:1289 +0x310
2021-09-21 13:50:32.656 [ERROR][16144] ipsets.go 561: Bad return code from 'ipset list'. error=exit status 1 family="inet" stderr="ipset v6.38: Kernel error received: Invalid argument\n"
2021-09-21 13:50:32.667 [ERROR][16144] ipsets.go 561: Bad return code from 'ipset list'. error=exit status 1 family="inet" stderr="ipset v6.38: Kernel error received: Invalid argument\n"
2021-09-21 13:50:32.677 [ERROR][16144] ipsets.go 561: Bad return code from 'ipset list'. error=exit status 1 family="inet" stderr="ipset v6.38: Kernel error received: Invalid argument\n"
2021-09-21 13:50:32.693 [ERROR][16144] ipsets.go 561: Bad return code from 'ipset list'. error=exit status 1 family="inet" stderr="ipset v6.38: Kernel error received: Invalid argument\n"
2021-09-21 13:50:32.711 [ERROR][16144] ipsets.go 561: Bad return code from 'ipset list'. error=exit status 1 family="inet" stderr="ipset v6.38: Kernel error received: Invalid argument\n"
2021-09-21 13:50:32.734 [ERROR][16144] ipsets.go 561: Bad return code from 'ipset list'. error=exit status 1 family="inet" stderr="ipset v6.38: Kernel error received: Invalid argument\n"
2021-09-21 13:50:32.772 [ERROR][16144] ipsets.go 561: Bad return code from 'ipset list'. error=exit status 1 family="inet" stderr="ipset v6.38: Kernel error received: Invalid argument\n"
2021-09-21 13:50:32.852 [ERROR][16144] ipsets.go 561: Bad return code from 'ipset list'. error=exit status 1 family="inet" stderr="ipset v6.38: Kernel error received: Invalid argument\n"
2021-09-21 13:50:32.995 [ERROR][16144] ipsets.go 561: Bad return code from 'ipset list'. error=exit status 1 family="inet" stderr="ipset v6.38: Kernel error received: Invalid argument\n"
2021-09-21 13:50:33.267 [ERROR][16144] ipsets.go 561: Bad return code from 'ipset list'. error=exit status 1 family="inet" stderr="ipset v6.38: Kernel error received: Invalid argument\n"
2021-09-21 13:50:33.794 [ERROR][16144] ipsets.go 916: Failed to read IP sets error=exit status 1 family="inet"
2021-09-21 13:50:33.794 [PANIC][16144] ipsets.go 342: Failed to update IP sets after multiple retries. family="inet"
```

**Comment by joedborg** [comment]
This is because `ip_set` is not included in the Nvidia kernel branch.
