### ISSUE TITLE
microk8s status --wait-ready hangs forever - Fedora 35

### ISSUE THREAD

**Issue by pacostas** [canonical/microk8s#2944]
I'm following below steps as mentioned on the installation https://microk8s.io/

`sudo snap install microk8s --classic`
`microk8s status --wait-ready`

And the `command microk8s status --wait-ready` hangs.

While is hanging, by hitting crtl+c I get below output:

```
Traceback (most recent call last):
  File "/snap/microk8s/2948/scripts/wrappers/status.py", line 223, in <module>
    isReady = wait_for_ready(timeout)
  File "/var/lib/snapd/snap/microk8s/2948/scripts/wrappers/common/utils.py", line 125, in wait_for_ready
    if is_cluster_ready():
  File "/var/lib/snapd/snap/microk8s/2948/scripts/wrappers/common/utils.py", line 54, in is_cluster_ready
    service_output = kubectl_get("all")
  File "/var/lib/snapd/snap/microk8s/2948/scripts/wrappers/common/utils.py", line 169, in kubectl_get
    return run("kubectl", kubeconfig, "get", cmd, "--all-namespaces", die=False)
  File "/var/lib/snapd/snap/microk8s/2948/scripts/wrappers/common/utils.py", line 35, in run
    args, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, env=env
  File "/snap/microk8s/2948/usr/lib/python3.6/subprocess.py", line 425, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/snap/microk8s/2948/usr/lib/python3.6/subprocess.py", line 863, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/snap/microk8s/2948/usr/lib/python3.6/subprocess.py", line 1534, in _communicate
    ready = selector.select(timeout)
  File "/snap/microk8s/2948/usr/lib/python3.6/selectors.py", line 376, in select
    fd_event_list = self._poll.poll(timeout)
KeyboardInterrupt
```

Details of the OS:
* Fedora 35 (Workstation Edition)
* 64-bit
* Gnome version 41.3
* Windowing System X11

I'm also attaching the tarball from the `microk8s inspect` command

file:///home/costas/Desktop/inspection-report-20220223_133744.tar.gz

Relevant PRs (where I didnt manage to solve my problem)
https://github.com/canonical/microk8s/issues/1246
https://github.com/canonical/microk8s/issues/2574

**Comment by pacostas** [comment]
> Hi @pacostas can you please attach the inspection tarball one more time?

updated, thank you :)

**Comment by balchua** [comment]
I was checking the logs.
K8sdqlite isnt starting due to this.

```
Feb 23 13:34:00 192.168.1.51 microk8s.daemon-k8s-dqlite[479837]: I0223 13:34:00.205408  479837 log.go:181] [ERROR] dqlite: proxy: first: remote -> local: remote error: tls: bad certificate
```
Was wondering what happened to the certificates being used by dqlite.

The `cluster.yaml` and `info.yaml` `ID` are not the same.

Info.yaml
```
Address: 127.0.0.1:19001
ID: 3297041220608546238
Role: 0
```
Cluster.yaml
```
- Address: 127.0.0.1:19001
  ID: 0
  Role: 0
```
