### ISSUE TITLE
calico container crashing in a loop and vxlan.calico no present on the host node

### ISSUE THREAD

**Issue by anubisg1** [canonical/microk8s#3157]
#### Summary
calico container crashing in a loop and vxlan.calico no present on the host node.
This is true for all the nodes in the cluster. i take just one as example

```
anubisg1@czsrc-lan-srv03:~$ ip link show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether e4:5f:01:47:3b:17 brd ff:ff:ff:ff:ff:ff
3: wlan0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether e4:5f:01:47:3b:18 brd ff:ff:ff:ff:ff:ff
4872: calic893cf18a63@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-fd20289f-4faf-41ac-4c02-c09ec4449bb0
13: cali361c03f256f@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-6e46c503-618f-4c74-4347-3d712054b729
4641: cali307d106f798@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-100af3e8-6f2c-2369-3346-9a01d28d05d4
4350: cali4050856b57c@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-48a11232-028c-1898-ae5b-e1018ebd2061
```

```
goroutine 115 [running]:
github.com/vishvananda/netlink.(*Handle).LinkList(0x0)
        /go/pkg/mod/github.com/vishvananda/netlink@v1.1.1-0.20210703095558-21f2c55a7727/link_linux.go:2008 +0x28
github.com/projectcalico/calico/felix/dataplane/linux.(*vxlanManager).getParentInterface(0x4000018100, 0x4000948780)
        /go/src/github.com/projectcalico/calico/felix/dataplane/linux/vxlan_mgr.go:480 +0x3c
github.com/projectcalico/calico/felix/dataplane/linux.(*vxlanManager).getLocalVTEPParent(0x4000018100)
        /go/src/github.com/projectcalico/calico/felix/dataplane/linux/vxlan_mgr.go:274 +0x34
github.com/projectcalico/calico/felix/dataplane/linux.(*vxlanManager).KeepVXLANDeviceInSync(0x4000018100, 0x5aa, 0x0, 0x2540be400)
        /go/src/github.com/projectcalico/calico/felix/dataplane/linux/vxlan_mgr.go:449 +0x240
created by github.com/projectcalico/calico/felix/dataplane/linux.NewIntDataplaneDriver
        /go/src/github.com/projectcalico/calico/felix/dataplane/linux/int_dataplane.go:448 +0x1434
W0520 12:01:16.804604 1217547 warnings.go:70] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
W0520 12:01:16.852772 1217547 warnings.go:70] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
2022-05-20 12:01:17.227 [ERROR][1217547] felix/route_table.go 951: Failed to get link attributes error=interface not present ifaceRegex="^vxlan.calico$" ipVersion=0x4 tableIndex=0
2022-05-20 12:01:17.448 [ERROR][1217547] felix/route_table.go 951: Failed to get link attributes error=interface not present ifaceRegex="^vxlan.calico$" ipVersion=0x4 tableIndex=0
2022-05-20 12:01:17.449 [ERROR][1217547] felix/route_table.go 951: Failed to get link attributes error=interface not present ifaceRegex="^vxlan.calico$" ipVersion=0x4 tableIndex=0
2022-05-20 12:01:17.464 [ERROR][1217547] felix/route_table.go 951: Failed to get link attributes error=interface not present ifaceRegex="^vxlan.calico$" ipVersion=0x4 tableIndex=0
2022-05-20 12:01:17.573 [ERROR][1217547] felix/route_table.go 951: Failed to get link attributes error=interface not present ifaceRegex="^vxlan.calico$" ipVersion=0x4 tableIndex=0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1670b28]
```

#### What Should Happen Instead?
vxlan.calico interface should be presetn and container functioning

#### Reproduction Steps
i just installed microk8s on ubuntu 22.04

#### Introspection Report
[inspection-report-20220520_140234.tar.gz](https://github.com/canonical/microk8s/files/8740419/inspection-report-20220520_140234.tar.gz)

#### Are you interested in contributing with a fix?

yes :)

**Comment by adubkov** [comment]
Same thing.

**Comment by andriilahuta** [comment]
#3087 seems to be related, installing `linux-modules-extra-raspi` resolved the issue for me.

**Comment by anubisg1** [comment]
I can confirm, this seems to be the case. It looks like that fixed it for me too
