### ISSUE TITLE
No yaml library in Microk8s namespace

### ISSUE THREAD

**Issue by r3d3mpt10n** [canonical/microk8s#3316]
#### Summary
Missing yaml library in microk8s namespace causes traceback with charmed-microk8s
https://github.com/canonical/charm-microk8s/issues/39

#### What Should Happen Instead?
If we have a script within the microk8s namespace that imports the  yaml library. We should ensure
the python3-yaml package is installed to avoid import errors.

#### Reproduction Steps
Deploy microk8s with juju with 3 nodes.

Observe nodes failing to join the cluster:
```
Unit         Workload  Agent  Machine  Public address  Ports                     Message
microk8s/4*  active    idle   4        172.20.13.50    80/tcp,443/tcp,16443/tcp  
microk8s/5   blocked   idle   5        172.20.13.93    80/tcp,443/tcp,16443/tcp  join failed, will try again
microk8s/6   blocked   idle   6        172.20.13.44    80/tcp,443/tcp,16443/tcp  join failed, will try again
```

They are trying to run microk8s using the binary within the snap filesystem:
https://github.com/canonical/charm-microk8s/blob/master/src/microk8scluster.py#L349

Which results in a traceback:
```
/snap/microk8s/3272/usr/bin/python3 /snap/microk8s/3272/scripts/cluster/join.py 192.168.50.99:25000/8d6aa24d3303a524650ef65dc72b0711/e467b5354473
Traceback (most recent call last):
  File "/snap/microk8s/3272/scripts/cluster/join.py", line 18, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

The library is available on the host, so we can use `microk8s join` without specifying the path to the snap binary. That works fine, but trying to execute from within the namespace causes the issue.

```
ubuntu@ubuntu:~$ juju ssh microk8s/5 -- /snap/microk8s/current/usr/bin/python3
Python 3.6.9 (default, Mar 15 2022, 13:55:28) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import yaml
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'yaml'
>>> quit()
Connection to 172.20.13.93 closed.
ubuntu@ubuntu:~$ juju ssh microk8s/5 -- python3
Python 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import yaml
>>> dir(yaml)
['AliasEvent', 'AliasToken', 'AnchorToken', 'BaseDumper', 'BaseLoader', 'BlockEndToken', 'BlockEntryToken', 'BlockMappingStartToken', 'BlockSequenceStartToken', 'CBaseDumper', 'CBaseLoader', 'CDumper', 'CFullLoader', 'CLoader', 'CSafeDumper', 'CSafeLoader', 'CUnsafeLoader', 'CollectionEndEvent', 'CollectionNode', 'CollectionStartEvent', 'DirectiveToken', 'DocumentEndEvent', 'DocumentEndToken', 'DocumentStartEvent', 'DocumentStartToken', 'Dumper', 'Event', 'FlowEntryToken', 'FlowMappingEndToken', 'FlowMappingStartToken', 'FlowSequenceEndToken', 'FlowSequenceStartToken', 'FullLoader', 'KeyToken', 'Loader', 'MappingEndEvent', 'MappingNode', 'MappingStartEvent', 'Mark', 'MarkedYAMLError', 'Node', 'NodeEvent', 'SafeDumper', 'SafeLoader', 'ScalarEvent', 'ScalarNode', 'ScalarToken', 'SequenceEndEvent', 'SequenceNode', 'SequenceStartEvent', 'StreamEndEvent', 'StreamEndToken', 'StreamStartEvent', 'StreamStartToken', 'TagToken', 'Token', 'UnsafeLoader', 'ValueToken', 'YAMLError', 'YAMLLoadWarning', 'YAMLObject', 'YAMLObjectMetaclass', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '__with_libyaml__', '_warnings_enabled', 'add_constructor', 'add_implicit_resolver', 'add_multi_constructor', 'add_multi_representer', 'add_path_resolver', 'add_representer', 'compose', 'compose_all', 'composer', 'constructor', 'cyaml', 'dump', 'dump_all', 'dumper', 'emit', 'emitter', 'error', 'events', 'full_load', 'full_load_all', 'io', 'load', 'load_all', 'load_warning', 'loader', 'nodes', 'parse', 'parser', 'reader', 'representer', 'resolver', 'safe_dump', 'safe_dump_all', 'safe_load', 'safe_load_all', 'scan', 'scanner', 'serialize', 'serialize_all', 'serializer', 'tokens', 'unsafe_load', 'unsafe_load_all', 'warnings']
```

#### Can you suggest a fix?
I will submit a PR. I think it's probably better if we just add python3-yaml to this namespace since we are shipping a script that imports the library.

#### Are you interested in contributing with a fix?
Yes. I'll send a PR for review. I'm not familiar with Snaps, so feel free to redirect as required.

**Comment by r3d3mpt10n** [comment]
I believe that isn't actually the issue. Just the way I was trying to replicate the issue actually by re-running the command from the journal logs:
```
Jul 11 06:10:44 juju-d73200-k8s-5 sudo[169946]:     root : TTY=unknown ; PWD=/var/lib/juju/agents/unit-microk8s-5/charm ; USER=root ; ENV=LD_LIBRARY_PATH=/snap/microk8s/3272/lib:/snap/micro
k8s/3272/usr/lib:/snap/microk8s/3272/lib/x86_64-linux-gnu:/snap/microk8s/3272/usr/lib/x86_64-linux-gnu ; COMMAND=/snap/microk8s/3272/usr/bin/python3 /snap/microk8s/3272/scripts/cluster/join
.py 192.168.50.162:25000/1881db41e70061519b87b6e4267dae77/4c2ba538e2da
```

I don't think this is actually an issue. I'll close this until I have found the actual problem
