### ISSUE TITLE
microk8s addons repo update core - failing

### ISSUE THREAD

**Issue by Aaron-Ritter** [canonical/microk8s#3392]
We've started 686d ago with our test k8s cluster, and upgraded the cluster through multiple core versions. I saw that some of the services got upgraded during these snap upgrades but I am unsure if the addon core repo got upgraded.

#### Summary
Is the core addon repo upgrading when upgrading the cluster, and if so do all the addons upgrade to the latest version as well?

```
sofo@k8s-test-m:~$ kubectl get no
NAME          STATUS   ROLES    AGE    VERSION
k8s-test-m    Ready    <none>   683d   v1.24.3-2+63243a96d1c393
k8s-test-n1   Ready    <none>   686d   v1.24.3-2+63243a96d1c393
k8s-test-n2   Ready    <none>   581d   v1.24.3-2+63243a96d1c393
```
based on my understanding because I only see 17 addons in the repo and the current githup repo https://github.com/canonical/microk8s-core-addons/tree/main/addons contains 21 addons it is not updated, in addition i don't see for example the kube-ovn in the list which i think i should?

in addition when it try to upgrade the core repo its failing.

#### What Should Happen Instead?
When upgrading the cluster the addons should upgrade as well, or at least there should be a clear instruction what to do with the addons during upgrade of the cluster.

#### Reproduction Steps
```
root@k8s-test-m:~# microk8s addons repo list
REPO       ADDONS SOURCE
core           17 /snap/microk8s/current/addons/core@84c902
```
```
root@k8s-test-m:~# microk8s addons repo update core
Updating repository core
Your configuration specifies to merge with the ref 'refs/heads/main'
from the remote, but no such ref was fetched.
Traceback (most recent call last):
  File "/snap/microk8s/3597/scripts/wrappers/addons.py", line 141, in <module>
    addons(prog_name="microk8s addons")
  File "/snap/microk8s/3597/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/snap/microk8s/3597/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/snap/microk8s/3597/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/snap/microk8s/3597/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/snap/microk8s/3597/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/microk8s/3597/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/snap/microk8s/3597/scripts/wrappers/addons.py", line 78, in update
    subprocess.check_call([GIT, "pull"], cwd=repo_dir)
  File "/snap/microk8s/3597/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/snap/microk8s/3597/git.wrapper', 'pull']' returned non-zero exit status 1.
```
when trying to upgrade for the first time it apparently tries a few things more but its failing, after that you see just the error above:
```
root@k8s-test-n2:~# microk8s addons repo update core
Updating repository core
remote: Counting objects: 41, done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 41 (delta 27), reused 24 (delta 11)
Unpacking objects: 100% (41/41), done.
From /snap/microk8s/current/addons/core
 * [new branch]      1.24       -> origin/1.24
Your configuration specifies to merge with the ref 'refs/heads/main'
from the remote, but no such ref was fetched.
Traceback (most recent call last):
  File "/snap/microk8s/3597/scripts/wrappers/addons.py", line 141, in <module>
    addons(prog_name="microk8s addons")
  File "/snap/microk8s/3597/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/snap/microk8s/3597/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/snap/microk8s/3597/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/snap/microk8s/3597/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/snap/microk8s/3597/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/microk8s/3597/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/snap/microk8s/3597/scripts/wrappers/addons.py", line 78, in update
    subprocess.check_call([GIT, "pull"], cwd=repo_dir)
  File "/snap/microk8s/3597/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/snap/microk8s/3597/git.wrapper', 'pull']' returned non-zero exit status 1.

root@k8s-test-n2:~# microk8s addons repo update core
Updating repository core
Your configuration specifies to merge with the ref 'refs/heads/main'
from the remote, but no such ref was fetched.
Traceback (most recent call last):
  File "/snap/microk8s/3597/scripts/wrappers/addons.py", line 141, in <module>
    addons(prog_name="microk8s addons")
  File "/snap/microk8s/3597/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/snap/microk8s/3597/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/snap/microk8s/3597/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/snap/microk8s/3597/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/snap/microk8s/3597/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/microk8s/3597/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/snap/microk8s/3597/scripts/wrappers/addons.py", line 78, in update
    subprocess.check_call([GIT, "pull"], cwd=repo_dir)
  File "/snap/microk8s/3597/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/snap/microk8s/3597/git.wrapper', 'pull']' returned non-zero exit status 1.

```

```
sofo@k8s-test-m:~$ microk8s status
microk8s is running
high-availability: yes
  datastore master nodes: 10.14.214.41:19001 10.14.214.40:19001 10.14.214.42:19001
  datastore standby nodes: none
addons:
  enabled:
    dns                  # (core) CoreDNS
    ha-cluster           # (core) Configure high availability on the current node
    helm3                # (core) Helm 3 - Kubernetes package manager
    metallb              # (core) Loadbalancer for your Kubernetes cluster
    metrics-server       # (core) K8s Metrics Server for API access to service metrics
    rbac                 # (core) Role-Based Access Control for authorisation
  disabled:
    community            # (core) The community addons repository
    dashboard            # (core) The Kubernetes dashboard
    gpu                  # (core) Automatic enablement of Nvidia CUDA
    helm                 # (core) Helm 2 - the package manager for Kubernetes
    host-access          # (core) Allow Pods connecting to Host services smoothly
    hostpath-storage     # (core) Storage class; allocates storage from host directory
    ingress              # (core) Ingress controller for external access
    mayastor             # (core) OpenEBS MayaStor
    prometheus           # (core) Prometheus operator for monitoring and logging
    registry             # (core) Private image registry exposed on localhost:32000
    storage              # (core) Alias to hostpath-storage add-on, deprecated
```

#### Introspection Report
tbd

#### Are you interested in contributing with a fix?
I am able to test, not sure how to fix this.

**Comment by Aaron-Ritter** [comment]
Thanks a lot @ktsakalozos, I was already looking in to adding the GitHub repo directly, adding the core from local repo I wasn't aware about.

But in both cases I am wondering now what the correct upgrade process should be for the already enabled addons:

```
addons:
  enabled:
    dns                  # (core) CoreDNS
    ha-cluster           # (core) Configure high availability on the current node
    metallb              # (core) Loadbalancer for your Kubernetes cluster
    metrics-server       # (core) K8s Metrics Server for API access to service metrics
    rbac                 # (core) Role-Based Access Control for authorisation
```

Just enabling it wont work as it will mention that the addon is already enabled, with disable enable i am not sure:

1. If the disabling will destroy/corrupt some of the already existing deployments e.g. metallb being used in existing services
2. If I am able to enable the addons with the same settings as 2 years ago e.g. with metallb
3. If I am not sure if for some of the addons what settings where used if I could extract them somewhere

```
root@k8s-test-m:~# microk8s enable dns
Infer repository core for addon dns
Addon core/dns is already enabled
```

What I would love to do is a upgrade but obviously that would require an additional process / script added in the addons, or the enable script being able to re-run with the already used settings.

**Comment by Aaron-Ritter** [comment]
by the way, why I was starting to looking at this is because I saw during rolling out all my deployments and daemonsets that some deprecated settings are still used for some of the cluster/addon related ressources:

```
sofo@k8s-test-m:~$ kubectl get deployment --all-namespaces | tail -n +2 | nawk '{ print "kubectl rollout restart deployment/"$2" -n "$1 " && sleep 1"}' | bash
......
Warning: spec.template.spec.nodeSelector[beta.kubernetes.io/os]: deprecated since v1.14; use "kubernetes.io/os" instead
deployment.apps/controller restarted
.....
Warning: spec.template.metadata.annotations[scheduler.alpha.kubernetes.io/critical-pod]: non-functional in v1.16+; use the "priorityClassName" field instead
deployment.apps/coredns restarted
.....
Warning: spec.template.metadata.annotations[scheduler.alpha.kubernetes.io/critical-pod]: non-functional in v1.16+; use the "priorityClassName" field instead
deployment.apps/calico-kube-controllers restarted
```

```
sofo@k8s-test-m:~$ kubectl get daemonset --all-namespaces | tail -n +2 | nawk '{ print "kubectl rollout restart daemonset/"$2" -n "$1 " && sleep 1"}' | bash
Warning: spec.template.spec.nodeSelector[beta.kubernetes.io/os]: deprecated since v1.14; use "kubernetes.io/os" instead
daemonset.apps/speaker restarted
Warning: spec.template.metadata.annotations[scheduler.alpha.kubernetes.io/critical-pod]: non-functional in v1.16+; use the "priorityClassName" field instead
daemonset.apps/calico-node restarted

```

**Comment by Aaron-Ritter** [comment]
@ktsakalozos thanks a lot for the fix! :)

About the correct addon upgrade procedure: As mentioned `microk8s addons repo update core` as well as `microk8s addons repo add core https://github.com/canonical/microk8s-core-addons --force` and `microk8s addons repo add core /snap/microk8s/current/addons/core --force` is updating the repository but its not actually updating the already enabled addons.

So should I open a issue about documenting the upgrade process of already enabled addons?

**Comment by ktsakalozos** [comment]
Hi @Aaron-Ritter,

When you update a repository you do not alter the hosted/running workloads you only update the enable & disable scripts. This may have some side effects.

- After a repository update the disable script might not be able to remove the workload already enabled. This may happen when the addon has been heavily updated. Such cases will not happen on patch releases (for example from 1.24.3 to 1.24.4) but may come up after a normal release eg from 1.24 to 1.25.
- Running workloads are not updated during cluster upgrades and this includes the workloads started via addons. Therefore if the workload/addon is using an API removed from upstream it will not function properly. Your best approach in this is to disable and re-enable any such addons.

I hope this explains some of the warnings you see on the logs.

**Comment by Aaron-Ritter** [comment]
Thanks @ktsakalozos, understood, but partially concerning:

especially if it comes to addons like rbac, dns, ha-cluster, disabling and enabling that is extremely intrusive as it affects the whole cluster. I am actually not sure if you even can properly disable/enable ha-cluster in a running cluster successfully. My first try caused me to completely delete microk8s from the node where i disabled ha-cluster.

Do you have a documentation how such an addon upgrade cycle should look like? From what i can see so far the only clean way would be to just build a new cluster from scratch in the new version instead.
