### ISSUE TITLE
upgrade from 1.24 to 1.25 fails on worker nodes

### ISSUE THREAD

**Issue by anubisg1** [canonical/microk8s#3408]
#### Summary
upgrading the snap fails

#### What Should Happen Instead?
should succeed

#### Reproduction Steps
```
anubisg1@czsrc-lan-srv04:~$ sudo snap refresh microk8s --classic --channel=1.25/stable
Handling re-refresh of "microk8s" as needed                                                                                                                        \
error: cannot perform the following tasks:
- Run configure hook of "microk8s" snap if present (run hook "configure": 
-----
+ '[' -e /var/snap/microk8s/3773/args/containerd-env ']'
+ grep -e KATA_PATH /var/snap/microk8s/3773/args/containerd-env
# KATA_PATH=
PATH=$PATH:$KATA_PATH
+ '[' -e /var/snap/microk8s/3773/args/containerd-template.toml ']'
+ grep -e io.containerd.kata.v2 /var/snap/microk8s/3773/args/containerd-template.toml
      runtime_type = "io.containerd.kata.v2"
+ for dir in ${SNAP_COMMON}/plugins ${SNAP_COMMON}/addons ${SNAP_DATA}/credentials/ ${SNAP_DATA}/certs/ ${SNAP_DATA}/args/ ${SNAP_DATA}/var/lock ${SNAP_DATA}/tmp/ ${SNAP_COMMON}/hooks
+ chmod -R ug+rwX /var/snap/microk8s/common/plugins
+ chmod -R o-rwX /var/snap/microk8s/common/plugins
+ for dir in ${SNAP_COMMON}/plugins ${SNAP_COMMON}/addons ${SNAP_DATA}/credentials/ ${SNAP_DATA}/certs/ ${SNAP_DATA}/args/ ${SNAP_DATA}/var/lock ${SNAP_DATA}/tmp/ ${SNAP_COMMON}/hooks
+ chmod -R ug+rwX /var/snap/microk8s/common/addons
+ chmod -R o-rwX /var/snap/microk8s/common/addons
+ for dir in ${SNAP_COMMON}/plugins ${SNAP_COMMON}/addons ${SNAP_DATA}/credentials/ ${SNAP_DATA}/certs/ ${SNAP_DATA}/args/ ${SNAP_DATA}/var/lock ${SNAP_DATA}/tmp/ ${SNAP_COMMON}/hooks
+ chmod -R ug+rwX /var/snap/microk8s/3773/credentials/
+ chmod -R o-rwX /var/snap/microk8s/3773/credentials/
+ for dir in ${SNAP_COMMON}/plugins ${SNAP_COMMON}/addons ${SNAP_DATA}/credentials/ ${SNAP_DATA}/certs/ ${SNAP_DATA}/args/ ${SNAP_DATA}/var/lock ${SNAP_DATA}/tmp/ ${SNAP_COMMON}/hooks
+ chmod -R ug+rwX /var/snap/microk8s/3773/certs/
+ chmod -R o-rwX /var/snap/microk8s/3773/certs/
+ for dir in ${SNAP_COMMON}/plugins ${SNAP_COMMON}/addons ${SNAP_DATA}/credentials/ ${SNAP_DATA}/certs/ ${SNAP_DATA}/args/ ${SNAP_DATA}/var/lock ${SNAP_DATA}/tmp/ ${SNAP_COMMON}/hooks
+ chmod -R ug+rwX /var/snap/microk8s/3773/args/
+ chmod -R o-rwX /var/snap/microk8s/3773/args/
+ for dir in ${SNAP_COMMON}/plugins ${SNAP_COMMON}/addons ${SNAP_DATA}/credentials/ ${SNAP_DATA}/certs/ ${SNAP_DATA}/args/ ${SNAP_DATA}/var/lock ${SNAP_DATA}/tmp/ ${SNAP_COMMON}/hooks
+ chmod -R ug+rwX /var/snap/microk8s/3773/var/lock
+ chmod -R o-rwX /var/snap/microk8s/3773/var/lock
+ for dir in ${SNAP_COMMON}/plugins ${SNAP_COMMON}/addons ${SNAP_DATA}/credentials/ ${SNAP_DATA}/certs/ ${SNAP_DATA}/args/ ${SNAP_DATA}/var/lock ${SNAP_DATA}/tmp/ ${SNAP_COMMON}/hooks
+ chmod -R ug+rwX /var/snap/microk8s/3773/tmp/
+ chmod -R o-rwX /var/snap/microk8s/3773/tmp/
+ for dir in ${SNAP_COMMON}/plugins ${SNAP_COMMON}/addons ${SNAP_DATA}/credentials/ ${SNAP_DATA}/certs/ ${SNAP_DATA}/args/ ${SNAP_DATA}/var/lock ${SNAP_DATA}/tmp/ ${SNAP_COMMON}/hooks
+ chmod -R ug+rwX /var/snap/microk8s/common/hooks
+ chmod -R o-rwX /var/snap/microk8s/common/hooks
++ get_microk8s_group
++ is_strict
++ cat /snap/microk8s/3773/meta/snap.yaml
++ grep -q strict
++ grep confinement
++ return 1
++ echo microk8s
+ group=microk8s
+ getent group microk8s
+ getent group microk8s
+ chgrp microk8s -R /var/snap/microk8s/common/plugins /var/snap/microk8s/common/addons /var/snap/microk8s/3773/credentials/ /var/snap/microk8s/3773/certs/ /var/snap/microk8s/3773/args/ /var/snap/microk8s/3773/var/lock/ /var/snap/microk8s/3773/var/kubernetes/backend/ /var/snap/microk8s/3773/tmp/ /var/snap/microk8s/common/hooks
+ is_strict
+ cat /snap/microk8s/3773/meta/snap.yaml
+ grep -q strict
+ grep confinement
+ return 1
+ try_copy_users_to_snap_microk8s
+ getent group microk8s
+ getent group snap_microk8s
+ echo 'One of the microk8s or snap_microk8s groups is missing'
One of the microk8s or snap_microk8s groups is missing
+ '[' -e /var/snap/microk8s/3773/opt/cni/bin/flanneld ']'
+ '[' -f /var/snap/microk8s/3773/args/flanneld ']'
+ grep -e etcd.socket:2379 /var/snap/microk8s/3773/args/etcd
+ grep -e basic-auth-file /var/snap/microk8s/3773/args/kube-apiserver
+ grep -e service-account-issuer /var/snap/microk8s/3773/args/kube-apiserver
--service-account-issuer='https://kubernetes.default.svc'
+ grep -e service-account-signing-key-file /var/snap/microk8s/3773/args/kube-apiserver
--service-account-signing-key-file=${SNAP_DATA}/certs/serviceaccount.key
+ grep -e feature-gates=RemoveSelfLink /var/snap/microk8s/3773/args/kube-apiserver
+ remove_docker_specific_args
+ grep -e '\-\-network-plugin' /var/snap/microk8s/3773/args/kubelet
+ grep -e '\-\-cni-conf-dir' /var/snap/microk8s/3773/args/kubelet
+ grep -e '\-\-cni-bin-dir' /var/snap/microk8s/3773/args/kubelet
+ return 1
+ grep -e --address= /var/snap/microk8s/3773/args/kube-scheduler
+ grep -e --address= /var/snap/microk8s/3773/args/kube-controller-manager
+ grep '\-\-enable\-v2' /var/snap/microk8s/3773/args/etcd
--enable-v2=true
+ '[' -e /var/snap/microk8s/3773/var/lock/clustered.lock ']'
+ grep -e '\-\-etcd-cafile /var/snap/microk8s/.*/ca.remote.crt' /var/snap/microk8s/3773/args/flanneld
+ grep -e '\-\-etcd-certfile /var/snap/microk8s/.*/server.remote.crt' /var/snap/microk8s/3773/args/flanneld
+ '[' -e /var/snap/microk8s/3773/args/flannel-template.conflist ']'
+ grep -e cniVersion /var/snap/microk8s/3773/args/flannel-template.conflist
    "cniVersion": "0.3.1",
+ '[' '!' -f /var/snap/microk8s/3773/args/cluster-agent ']'
+ grep -e '\-\-timeout' /var/snap/microk8s/3773/args/cluster-agent
--timeout 240
+ grep -e '\-\-ip-masq' /var/snap/microk8s/3773/args/flanneld
--ip-masq=true
+ grep -e '\-\-cluster-cidr=10.152.183.0/24' /var/snap/microk8s/3773/args/kube-proxy
+ '[' -e /var/snap/microk8s/3773/var/lock/stopped.lock ']'
+ '[' -e /var/snap/microk8s/3773/var/lock/lite.lock ']'
+ '[' -e /var/snap/microk8s/3773/args/kubelite ']'
+ grep -e '\-\-insecure\-port' /var/snap/microk8s/3773/args/kube-apiserver
+ '[' -e /var/snap/microk8s/3773/args/k8s-dqlite ']'
+ '[' -e /snap/microk8s/3773/default-args/k8s-dqlite ']'
+ '[' -e /var/snap/microk8s/3773/args/k8s-dqlite ']'
+ refresh_calico_if_needed
+ /snap/microk8s/3773/usr/bin/python3 /snap/microk8s/3773/scripts/calico/upgrade.py
Traceback (most recent call last):
  File "/snap/microk8s/3773/scripts/calico/upgrade.py", line 192, in <module>
    main()
  File "/snap/microk8s/3773/scripts/calico/upgrade.py", line 188, in main
    mark_apply_needed(cni_reapply_lock_file)
  File "/snap/microk8s/3773/scripts/calico/upgrade.py", line 171, in mark_apply_needed
    os.remove(lock_file)
FileNotFoundError: [Errno 2] No such file or directory: '/var/snap/microk8s/3773/var/lock/cni-loaded'
-----)
```

**Comment by ktsakalozos** [comment]
Thank you for reporting this @anubisg1. I was not able to reproduce under normal conditions the error you are seeing. Only by manually deleting the `/var/snap/microk8s/3773/var/lock/cni-loaded` I managed to get this error.

In any case, the provided PR addresses the issue by not failing the refresh if the file is already missing.
