### ISSUE TITLE
`microk8s enable dns hostpath-storage` fails with an exception

### ISSUE THREAD

**Issue by barrettj12** [canonical/microk8s#3539]
#### Summary

`microk8s enable dns hostpath-storage` fails with an exception. This issue seems to be intermittent, as this only happens sometimes. See [this test run](https://github.com/juju/juju/actions/runs/3384583857/jobs/5621785225).

```console
$ sudo snap install microk8s --channel=1.25-strict/stable
microk8s (1.25-strict/stable) v1.25.2 from Canonical** installed
$ sudo usermod -a -G snap_microk8s runner
$ newgrp snap_microk8s
$ sudo microk8s enable dns hostpath-storage
Traceback (most recent call last):
  File "/snap/microk8s/40[49](https://github.com/juju/juju/actions/runs/3384583857/jobs/5621785225#step:7:50)/scripts/wrappers/enable.py", line 41, in <module>
    enable(prog_name="microk8s enable")
  File "/snap/microk8s/4049/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/snap/microk8s/4049/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/snap/microk8s/4049/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/microk8s/4049/usr/lib/python3/dist-packages/click/core.py", line [53](https://github.com/juju/juju/actions/runs/3384583857/jobs/5621785225#step:7:54)5, in invoke
    return callback(*args, **kwargs)
  File "/snap/microk8s/4049/scripts/wrappers/enable.py", line 37, in enable
    xable("enable", addons)
  File "/snap/microk8s/4049/scripts/wrappers/common/utils.py", line 445, in xable
    enabled_addons_info, disabled_addons_info = get_status(available_addons_info, True)
  File "/snap/microk8s/4049/scripts/wrappers/common/utils.py", line 491, in get_status
    kube_output = kubectl_get("all,ingress")
  File "/snap/microk8s/4049/scripts/wrappers/common/utils.py", line 216, in kubectl_get
    return run(KUBECTL, "get", cmd, "--all-namespaces", die=False)
  File "/snap/microk8s/4049/scripts/wrappers/common/utils.py", line 74, in run
    result.check_returncode()
  File "/snap/microk8s/4049/usr/lib/python3.6/subprocess.py", line 389, in check_returncode
    self.stderr)
subprocess.CalledProcessError: Command '('/snap/microk8s/4049/microk8s-kubectl.wrapper', 'get', 'all,ingress', '--all-namespaces')' returned non-zero exit status 1.
```

**Comment by berkayoz** [comment]
Hey @barrettj12,
I could not reproduce this, however I have a suspicion that the api-server might not be ready when the `enable` command is called. It takes a small bit of time until the cluster is ready, so it feels like calling the `enable` command right after the install could lead to this issue. I'd suggest adding `microk8s status --wait-ready` before the `enable` command to make sure the cluster is ready.

**Comment by barrettj12** [comment]
Thanks @berkayoz, I've done this and it seems to fix the issue. Would it be possible for microk8s to handle this internally though? Surfacing exceptions is generally a bad look - they should be handled somewhere.
