### ISSUE TITLE
Updating community repository failed

### ISSUE THREAD

**Issue by briantilburgs** [canonical/microk8s#3730]
Hi canonical,

I really like microk8s and want to try the fluentd but there is a problem updating de repository:

rgs@home-kube01:~$ microk8s addons repo update community
Updating repository community
Traceback (most recent call last):
  File "/snap/microk8s/4567/scripts/wrappers/addons.py", line 346, in <module>
    addons(prog_name="microk8s addons")
  File "/snap/microk8s/4567/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/snap/microk8s/4567/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/snap/microk8s/4567/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/snap/microk8s/4567/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/snap/microk8s/4567/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/microk8s/4567/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/snap/microk8s/4567/scripts/wrappers/addons.py", line 258, in update
    [GIT, "rev-parse", "--abbrev-ref", "HEAD"], cwd=remote_url, stderr=subprocess.DEVNULL
  File "/snap/microk8s/4567/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/snap/microk8s/4567/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/snap/microk8s/4567/git.wrapper', 'rev-parse', '--abbrev-ref', 'HEAD']' returned non-zero exit status 128.

Fluentd is not yet in the list.

urgs@home-kube01:~$ snap info microk8s
name:      microk8s
snap-id:      EaXqgt1lyCaxKaQCU349mlodBkDCXRcg
tracking:     1.26/stable
refresh-date: today at 05:08 CET
installed:               v1.26.1                    (4567) 148MB classic

Running a cluster on 3 Raspberry pi4 :-)

**Comment by ktsakalozos** [comment]
Hi @briantilburgs what do you see with `microk8s.addons repo list`? Is the community repo enabled?

**Comment by ktsakalozos** [comment]
Could you also please try to update the repository with `sudo`, ie `sudo microk8s addons repo update community` ?

**Comment by neoaggelos** [comment]
Hi @briantilburgs,

Also, keep in mind that the Fluentd is not available for arm64 architectures, only amd64 at the moment. Contributions are welcome!

See https://github.com/canonical/microk8s-community-addons/blob/main/addons.yaml#L29-L34

**Comment by briantilburgs** [comment]
> Hi @briantilburgs what do you see with `microk8s.addons repo list`? Is the community repo enabled?

kube01:~$ microk8s.addons repo list
REPO       ADDONS SOURCE
core           20 (built-in)
community      11 /snap/microk8s/current/addons/community@e92e03

**Comment by briantilburgs** [comment]
> Hi @briantilburgs,
> 
> Also, keep in mind that the Fluentd is not available for arm64 architectures, only amd64 at the moment. Contributions are welcome!
> 
> See https://github.com/canonical/microk8s-community-addons/blob/main/addons.yaml#L29-L34

Thanks, that must be the issue..
