### ISSUE TITLE
microk8s enable/disable not working after update to 1.27/stable

### ISSUE THREAD

**Issue by wh-zfy** [canonical/microk8s#3918]
#### Summary
After updating from v1.26.3 to 1.27/stable no add-on can be enabled/disabled anymore.

```
$ microk8s enable observability
Traceback (most recent call last):
  File "/snap/microk8s/5101/scripts/wrappers/enable.py", line 41, in <module>
    enable(prog_name="microk8s enable")
  File "/snap/microk8s/5101/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/snap/microk8s/5101/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/snap/microk8s/5101/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/microk8s/5101/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/snap/microk8s/5101/scripts/wrappers/enable.py", line 37, in enable
    xable("enable", addons)
  File "/snap/microk8s/5101/scripts/wrappers/common/utils.py", line 477, in xable
    protected_xable(action, addon_args)
  File "/snap/microk8s/5101/scripts/wrappers/common/utils.py", line 488, in protected_xable
    with open(lock_file_path, "w") as f:
PermissionError: [Errno 13] Permission denied: '/var/snap/microk8s/common/.microk8s-addon-lock'
```

#### What Should Happen Instead?
enabling/disabling of plugins should still work.

#### Reproduction Steps
The issue consistently appears after updating and disappears after reverting to the previous version.

1. 
```
$ microk8s version
MicroK8s v1.26.3 revision 4959
```
2.
```
$ sudo snap refresh microk8s --channel=1.27/stable
microk8s (1.27/stable) v1.27.0 from Canonical✓ refreshed
```
3.
```
$ microk8s enable observability
Traceback (most recent call last):
  File "/snap/microk8s/5101/scripts/wrappers/enable.py", line 41, in <module>
    enable(prog_name="microk8s enable")
  File "/snap/microk8s/5101/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/snap/microk8s/5101/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/snap/microk8s/5101/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/microk8s/5101/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/snap/microk8s/5101/scripts/wrappers/enable.py", line 37, in enable
    xable("enable", addons)
  File "/snap/microk8s/5101/scripts/wrappers/common/utils.py", line 477, in xable
    protected_xable(action, addon_args)
  File "/snap/microk8s/5101/scripts/wrappers/common/utils.py", line 488, in protected_xable
    with open(lock_file_path, "w") as f:
PermissionError: [Errno 13] Permission denied: '/var/snap/microk8s/common/.microk8s-addon-lock'
```
```
$ ls -lah /var/snap/microk8s/common/
total 36K
drwxr-xr-x 9 root root     4.0K Apr 12 23:06 .
drwxr-xr-x 6 root root     4.0K Apr 12 23:48 ..
drwxrwx--- 4 root microk8s 4.0K Apr 10 17:38 addons
drwxr-xr-x 7 root root     4.0K Apr 11 14:04 default-storage
drwxr-xr-x 3 root root     4.0K Apr 12 23:06 etc
drwxrwx--- 5 root microk8s 4.0K Mar 24 11:34 hooks
drwxrwx--- 2 root microk8s 4.0K Mar 24 11:34 plugins
drwxr-xr-x 3 root root     4.0K Apr 12 23:50 run
drwx--x--x 4 root root     4.0K Mar 24 11:34 var
```
4.
```
$ sudo snap revert microk8s
microk8s reverted to v1.26.3
```
5.
```
$ microk8s enable observability
Infer repository core for addon observability
Addon core/dns is already enabled
Addon core/helm3 is already enabled
Addon core/hostpath-storage is already enabled
Enabling observability
[...]

Note: the observability stack is setup to monitor only the current nodes of the MicroK8s cluster.
For any nodes joining the cluster at a later stage this addon will need to be set up again.

Observability has been enabled (user/pass: [...])

```

**Comment by ktsakalozos** [comment]
Hi @wh-zfy, thank you for reporting this.

The problem appears when the user is a member of the microk8s group and tries to enable an addon on the 1.27 for the first time.

We are working on a fix. For now a workaround is to use `sudo` the first time you enable an addon. This will set the right permissions and all consecutive enable commands will not have this issue.

**Comment by wh-zfy** [comment]
Hi @ktsakalozos, thanks for your fast reply.

I can confirm that my user is in the microk8s group and it was the first time to activate an addon after the update.
Using sudo the activation worked and after this it was also possible to activate/deactivate addons without sudo.

**Comment by ktsakalozos** [comment]
The fix is merged and we will ship it within the day. Apologies for the inconvenience.

**Comment by ktsakalozos** [comment]
The fix is released. Thank you again @wh-zfy for bringing it to our attention.
