### ISSUE TITLE
equests.exceptions.HTTPError: 404 Client Error:

### ISSUE THREAD

**Issue by kabalambi03** [canonical/microk8s#3926]
I am having this error when i try run "microstack boot strap.

rain@microstack:~$ microstack -v bootstrap
[12:26:55] DEBUG    Updating /home/rain/snap/microstack/common/etc/deploy from /snap/microstack/386/etc/deploy...                                                            bootstrap.py:110
           DEBUG    Bootstrap node: role CONVERGED                                                                                                                           bootstrap.py:116
           DEBUG    Starting pre-flight check Check for juju snap                                                                                                            bootstrap.py:135
Checking for presence of Juju ... done
           DEBUG    Starting pre-flight check Check for microk8s snap                                                                                                        bootstrap.py:135
Checking for presence of microk8s ... done
           DEBUG    Starting pre-flight check Check for openstack-hypervisor snap                                                                                            bootstrap.py:135
Checking for presence of openstack-hypervisor ... done
           DEBUG    Starting pre-flight check Check health of openstack-hypervisor snap                                                                                      bootstrap.py:135
           DEBUG    http://localhost:None "GET /health HTTP/1.1" 404 22                                                                                                 connectionpool.py:456
Traceback (most recent call last):
  File "/snap/microstack/386/bin/microstack", line 8, in <module>
    sys.exit(main())
  File "/snap/microstack/386/lib/python3.10/site-packages/sunbeam/main.py", line 58, in main
    cli()
  File "/snap/microstack/386/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/snap/microstack/386/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/snap/microstack/386/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/snap/microstack/386/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/microstack/386/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/snap/microstack/386/lib/python3.10/site-packages/sunbeam/commands/bootstrap.py", line 138, in bootstrap
    result = check.run()
  File "/snap/microstack/386/lib/python3.10/site-packages/sunbeam/jobs/checks.py", line 132, in run
    hypervisor_health = client.health.get_health()
  File "/snap/microstack/386/lib/python3.10/site-packages/sunbeam/ohv_config/config.py", line 197, in get_health
    return self._get("/health")
  File "/snap/microstack/386/lib/python3.10/site-packages/sunbeam/ohv_config/service.py", line 79, in _get
    return self._request("get", path, **kwargs)
  File "/snap/microstack/386/lib/python3.10/site-packages/sunbeam/ohv_config/service.py", line 73, in _request
    raise e
  File "/snap/microstack/386/lib/python3.10/site-packages/sunbeam/ohv_config/service.py", line 68, in _request
    response.raise_for_status()
  File "/snap/microstack/386/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+unix://%2Fvar%2Fsnap%2Fmicrostack%2F386%2Fhypervisor-config%2Funix.socket/health

**Comment by neoaggelos** [comment]
Hi @kabalambi03, this looks like an issue with [MicroStack](https://microstack.run) instead. You can report the bug at https://bugs.launchpad.net/microstack/+filebug.

Thanks!
