### ISSUE TITLE
enabling mayastor does not create the storage of /dev/disk/by-uuid on Virtual machines

### ISSUE THREAD

**Issue by narindergupta** [canonical/microk8s#3946]
Create a Microk8s cluster and trying to enable the mayastor plugin, After enabling the plugin i can list the storage from the local disk rootfs. When i tried to create a new storage using the file below

cat msppool
apiVersion: "openebs.io/v1alpha1"
kind: MayastorPool
metadata:
name: microk8s-kafka-cos3-pool2
namespace: mayastor
spec:
node: kafka-cos3
disks: ["/dev/disk/by-uuid/?????????????????????????"]

microk8s kubectl get msp
NAME NODE STATUS CAPACITY USED AVAILABLE
microk8s-kafka-cos1-pool kafka-cos1 Online 21449670656 0 21449670656
microk8s-kafka-cos3-pool2 kafka-cos3 Error 0 0 0

**Comment by neoaggelos** [comment]
Hi @narindergupta, unfortunately I cannot reproduce the issue that you are describing. Can you check the output of `lsblk -f` on the host and verify that the uuid matches?

In a test setup, I have:

```
ubuntu@t-1:~$ lsblk -f /dev/vdd
NAME FSTYPE LABEL UUID                                 FSAVAIL FSUSE% MOUNTPOINT
vdd

ubuntu@t-1:~$ sudo mkfs.ext4 /dev/vdd
mke2fs 1.46.2 (28-Feb-2021)
Discarding device blocks: done                            
Creating filesystem with 2621440 4k blocks and 655360 inodes
Filesystem UUID: 5fd466a9-34f8-40f1-948e-5fe27f6bc874
Superblock backups stored on blocks: 
	32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (16384 blocks): done
Writing superblocks and filesystem accounting information: done 

ubuntu@t-1:~$ lsblk -f /dev/vdd
NAME FSTYPE LABEL UUID                                 FSAVAIL FSUSE% MOUNTPOINT
vdd  ext4         5fd466a9-34f8-40f1-948e-5fe27f6bc874                

ubuntu@t-1:~$ cat msp.yaml 
apiVersion: openebs.io/v1alpha1
kind: MayastorPool
metadata:
  name: test
  namespace: mayastor
spec:
  node: t-1
  disks:
    - /dev/disk/by-uuid/5fd466a9-34f8-40f1-948e-5fe27f6bc874

ubuntu@t-1:~$ k get msp -n mayastor
NAME                NODE   STATUS   CAPACITY      USED   AVAILABLE
microk8s-t-1-pool   t-1    Online   21449670656   0      21449670656
test                t-1    Online   10724835328   0      10724835328

ubuntu@t-1:~$ k exec -it -n mayastor ds/mayastor-csi -- ls /dev/disk/by-uuid
Defaulted container "mayastor-csi" out of: mayastor-csi, csi-driver-registrar
5fd466a9-34f8-40f1-948e-5fe27f6bc874  b8febffc-8e48-460b-9e20-1ce7f2c46d16
A1F3-1E55            
```

What happens if you try these commands in your own case?

**Comment by narindergupta** [comment]
here are the information where i am getting issues. Only difference is I am trying the diskpool while in case of msp i am getting this error

microk8s kubectl get msp -n mayastor
error: the server doesn't have a resource type "msp"

microk8s mayastor-pools list
Traceback (most recent call last):
  File "/var/snap/microk8s/common/plugins/mayastor-pools", line 146, in <module>
    pools.main()
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/var/snap/microk8s/common/plugins/mayastor-pools", line 107, in list
    subprocess.run([KUBECTL, "get", "diskpool", "-n", "mayastor"])
  File "/snap/microk8s/5141/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/snap/microk8s/5141/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/snap/microk8s/5141/usr/lib/python3.8/subprocess.py", line 1639, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
TypeError: fork_exec() takes exactly 21 arguments (17 given)


microk8s kubectl get diskpool -n mayastor
NAME                       NODE         STATUS   CAPACITY      USED   AVAILABLE
microk8s-kafka-cos2-pool   kafka-cos2   Online   21449670656   0      21449670656
microk8s-kafka-cos1-pool   kafka-cos1   Online   21449670656   0      21449670656
microk8s-kafka-cos3-pool   kafka-cos3   Online   21449670656   0      21449670656

cat msp.yaml 
apiVersion: openebs.io/v1alpha1
kind: DiskPool
metadata:
  name: test
  namespace: mayastor
spec:
  node: kafka-cos1
  disks:
    - /dev/disk/by-uuid/44d8eb81-4ca2-4bb7-a4f1-105559683c1b

 microk8s kubectl get dsp -n mayastor
NAME                       NODE         STATUS     CAPACITY      USED   AVAILABLE
microk8s-kafka-cos2-pool   kafka-cos2   Online     21449670656   0      21449670656
microk8s-kafka-cos1-pool   kafka-cos1   Online     21449670656   0      21449670656
microk8s-kafka-cos3-pool   kafka-cos3   Online     21449670656   0      21449670656
test                       kafka-cos1   Creating   0             0      0

It stucks in test for long time.

I am using 1.27 microk8s ckuster for K8s on Azure gov cloud.

**Comment by narindergupta** [comment]
getting some timeout error in mayastor operator.

  Apr 22 04:15:06.427 ERROR openapi::clients::tower::configuration: failed to issue request, error: request timed out
    at openapi/src/clients/tower/configuration.rs:113
    in openapi::clients::tower::configuration::HTTP with ^[[1mhttp.method^[[0m: PUT, ^[[1mhttp.url^[[0m: http://rest:8081/v0/nodes/kafka-cos1/pools/test, ^[[1motel.name^[[0m: PUT http://rest:8081/v0/nodes/kafka-cos1/pools/test, ^[[1motel.kind^[[0m: client, ^[[1motel.status_code^[[0m: "ERROR"
    in msp_operator::create_or_import with ^[[1mname^[[0m: "test", ^[[1mstatus^[[0m: Some(MayastorPoolStatus { state: Creating, capacity: 0, used: 0, available: 0 })
    in msp_operator::reconcile with ^[[1mname^[[0m: kafka-cos1, ^[[1mstatus^[[0m: Some(MayastorPoolStatus { state: Creating, capacity: 0, used: 0, available: 0 })
    in kube_runtime::controller::reconciling object with ^[[1mobject.ref^[[0m: MayastorPool.v1alpha1.openebs.io/test.mayastor, ^[[1mobject.reason^[[0m: error policy requested retry

  Apr 22 04:15:06.428  WARN msp_operator: HTTP request error: error in request: request timed out, retry scheduled @Sat, 22 Apr 2023 04:15:11 +0000 (5 seconds from now)
    at control-plane/msp-operator/src/main.rs:825
    in kube_runtime::controller::reconciling object with ^[[1mobject.ref^[[0m: MayastorPool.v1alpha1.openebs.io/test.mayastor, ^[[1mobject.reason^[[0m: error policy requested retry

  Apr 22 04:15:11.448 ERROR openapi::clients::tower::configuration: failed to issue request, status: 500 Internal Server Error
    at openapi/src/clients/tower/configuration.rs:110
    in openapi::clients::tower::configuration::HTTP with ^[[1mhttp.method^[[0m: PUT, ^[[1mhttp.url^[[0m: http://rest:8081/v0/nodes/kafka-cos1/pools/test, ^[[1motel.name^[[0m: PUT http://rest:8081/v0/nodes/kafka-cos1/pools/test, ^[[1motel.kind^[[0m: client, ^[[1mhttp.status_code^[[0m: 500, ^[[1motel.status_code^[[0m: "ERROR", ^[[1motel.status_code^[[0m: "ERROR", ^[[1mhttp.status_code^[[0m: 500
    in msp_operator::create_or_import with ^[[1mname^[[0m: "test", ^[[1mstatus^[[0m: Some(MayastorPoolStatus { state: Creating, capacity: 0, used: 0, available: 0 })
    in msp_operator::reconcile with ^[[1mname^[[0m: kafka-cos1, ^[[1mstatus^[[0m: Some(MayastorPoolStatus { state: Creating, capacity: 0, used: 0, available: 0 })
    in kube_runtime::controller::reconciling object with ^[[1mobject.ref^[[0m: MayastorPool.v1alpha1.openebs.io/test.mayastor, ^[[1mobject.reason^[[0m: error policy requested retry

**Comment by narindergupta** [comment]
looked into mayastor logs and here are the details.

*[2023-04-22T04:00:39.270986114+00:00  INFO mayastor::bdev::nexus::nexus_module:nexus_module.rs:36] Initializing Nexus CAS Module
[2023-04-22T04:00:39.271530120+00:00  INFO mayastor::core::reactor:reactor.rs:175] scheduled mayastor_nvmf_tcp_pg_core_1 0x559ce49b6e60 on core:1
[2023-04-22T04:00:39.342116578+00:00  INFO mayastor::subsys::nvmf::target:target.rs:262] nvmf target listening on 172.24.8.72:(4421,8420)
[2023-04-22T04:00:39.342197579+00:00  INFO mayastor::subsys::nvmf::target:target.rs:353] nvmf target accepting new connections and is ready to roll..💃
[2023-04-22T04:00:39.423471051+00:00  INFO mayastor::core::reactor:reactor.rs:175] scheduled iscsi_poll_group_1 0x559ce49eef60 on core:1
[2023-04-22T04:00:39.423549352+00:00  INFO mayastor::core::env:env.rs:584] RPC server listening at: /var/tmp/mayastor.sock
[2023-04-22T04:00:39.472386877+00:00  INFO mayastor::persistent_store:persistent_store.rs:82] Connected to etcd on endpoint etcd-client:2379
[2023-04-22T04:00:39.472463577+00:00  INFO mayastor::subsys::registration::registration_grpc:registration_grpc.rs:153] Registering '"kafka-cos1"' with grpc server 172.24.8.72:10124 ...
[2023-04-22T04:00:39.472651479+00:00  INFO mayastor::grpc::server:server.rs:33] gRPC server configured at address 172.24.8.72:10124
[2023-04-22T04:00:42.587659721+00:00 ERROR mayastor::lvs::lvs_pool:lvs_pool.rs:295] error=failed to import pool microk8s-kafka-cos1-pool
[2023-04-22T04:00:42.650110791+00:00  INFO mayastor::lvs::lvs_pool:lvs_pool.rs:412] The pool 'microk8s-kafka-cos1-pool' has been created on /data/microk8s.img
[2023-04-22T04:14:41.434894283+00:00 ERROR mayastor::lvs::lvs_pool:lvs_pool.rs:295] error=failed to import pool test
[2023-04-22T04:14:51.428954373+00:00  WARN mayastor::grpc::mayastor_grpc:mayastor_grpc.rs:100] create_pool: gRPC method timed out, args: CreatePoolRequest { name: "test", disks: ["/dev/disk/by-uuid/73c18c24-9913-4213-babc-d50daaf8cc81"] }
[2023-04-22T04:14:51.454851745+00:00 ERROR mayastor::lvs::lvs_pool:lvs_pool.rs:295] error=failed to import pool test
[2023-04-22T04:14:51.454927346+00:00 ERROR mayastor::spdk:lvol.c:627] lvolstore with name test already exists   
[2023-04-22T04:14:56.432277158+00:00  WARN mayastor::grpc::mayastor_grpc:mayastor_grpc.rs:100] create_pool: gRPC method timed out, args: CreatePoolRequest { name: "test", disks: ["/dev/disk/by-uuid/73c18c24-9913-4213-babc-d50daaf8cc81"] }
[2023-04-22T04:15:02.228887234+00:00  INFO mayastor::lvs::lvs_pool:lvs_pool.rs:412] The pool 'test' has been created on /dev/disk/by-uuid/73c18c24-9913-4213-babc-d50daaf8cc81
[2023-04-22T04:15:02.228967335+00:00 ERROR mayastor::core::thread:thread.rs:219] Failed to send response future result Ok(Pool { name: "test", disks: [""], state: PoolOnline, capacity: 4393747349504, used: 0 })
[2023-04-22T04:15:11.441559019+00:00  WARN mayastor::grpc::mayastor_grpc:mayastor_grpc.rs:100] create_pool: gRPC method timed out, args: CreatePoolRequest { name: "test", disks: ["/dev/disk/by-uuid/73c18c24-9913-4213-babc-d50daaf8cc81"] }
[2023-04-22T04:15:11.441648920+00:00 ERROR mayastor::lvs::lvs_pool:lvs_pool.rs:423] error=errno: EEXIST: File exists failed to create pool test
[2023-04-22T04:15:16.457338575+00:00 ERROR mayastor::lvs::lvs_pool:lvs_pool.rs:423] error=errno: EEXIST: File exists failed to create pool test
[2023-04-22T04:15:21.471553364+00:00 ERROR mayastor::lvs::lvs_pool:lvs_pool.rs:423] error=errno: EEXIST: File exists failed to create pool test
**

**Comment by narindergupta** [comment]
microk8s kubectl get msp -n mayastor
NAME NODE STATUS CAPACITY USED AVAILABLE
microk8s-kafka-cos1-pool kafka-cos1 Online 21449670656 0 21449670656
microk8s-kafka-cos3-pool kafka-cos3 Online 21449670656 0 21449670656
microk8s-kafka-cos2-pool kafka-cos2 Online 21449670656 0 21449670656
test kafka-cos1 Creating 0 0 0

Apr 22 04:15:06.442 ERROR core::pool::service: error: gRPC request 'create_pool' for 'Pool' failed with 'status: Cancelled, message: "Timeout expired", details: [], metadata: MetadataMap { headers: {} }'
at control-plane/agents/core/src/pool/service.rs:240

Apr 22 04:15:11.447 ERROR core::pool::service: error: gRPC request 'create_pool' for 'Pool' failed with 'status: Internal, message: "errno: EEXIST: File exists failed to create pool test", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Sat, 22 Apr 2023 04:15:11 GMT"} }'
at control-plane/agents/core/src/pool/service.rs:240

Apr 22 04:15:16.461 ERROR core::pool::service: error: gRPC request 'create_pool' for 'Pool' failed with 'status: Internal, message: "errno: EEXIST: File exists failed to create pool test", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Sat, 22 Apr 2023 04:15:16 GMT"} }'
at control-plane/agents/core/src/pool/service.rs:240

Apr 22 04:15:21.477 ERROR core::pool::service: error: gRPC request 'create_pool' for 'Pool' failed with 'status: Internal, message: "errno: EEXIST: File exists failed to create pool test", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Sat, 22 Apr 2023 04:15:21 GMT"} }'
at control-plane/agents/core/src/pool/service.rs:240

Apr 22 04:15:26.496 ERROR core::pool::service: error: gRPC request 'create_pool' for 'Pool' failed with 'status: Internal, message: "errno: EEXIST: File exists failed to create pool test", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Sat, 22 Apr 2023 04:15:26 GMT"} }'
at control-plane/agents/core/src/pool/service.rs:240

Apr 22 04:15:31.512 ERROR core::pool::service: error: gRPC request 'create_pool' for 'Pool' failed with 'status: Internal, message: "errno: EEXIST: File exists failed to create pool test", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Sat, 22 Apr 2023 04:15:31 GMT"} }'
at control-plane/agents/core/src/pool/service.rs:240
