### ISSUE TITLE
microk8s 1.27 error accessing EKS 1.26?

### ISSUE THREAD

**Issue by khteh** [canonical/microk8s#3955]
#### Summary

```
$ k version
Error processing line 1 of /usr/lib/python3/dist-packages/google_auth-1.5.1-nspkg.pth:

Fatal Python error: init_import_site: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "<frozen site>", line 192, in addpackage
  File "<string>", line 1, in <module>
  File "<frozen importlib.util>", line 2, in <module>
ModuleNotFoundError: No module named 'importlib._abc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 982, in exec_module
  File "<frozen site>", line 635, in <module>
  File "<frozen site>", line 622, in main
  File "<frozen site>", line 403, in addsitepackages
  File "<frozen site>", line 232, in addsitedir
  File "<frozen site>", line 202, in addpackage
  File "/snap/microk8s/5250/usr/lib/python3.8/traceback.py", line 5, in <module>
    import linecache
  File "/snap/microk8s/5250/usr/lib/python3.8/linecache.py", line 11, in <module>
    import tokenize
  File "/snap/microk8s/5250/usr/lib/python3.8/tokenize.py", line 32, in <module>
    import re
  File "/snap/microk8s/5250/usr/lib/python3.8/re.py", line 125, in <module>
    import sre_compile
  File "/snap/microk8s/5250/usr/lib/python3.8/sre_compile.py", line 17, in <module>
    assert _sre.MAGIC == MAGIC, "SRE module mismatch"
           ^^^^^^^^^^^^^^^^^^^
AssertionError: SRE module mismatch
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-25T19:00:00Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Unable to connect to the server: getting credentials: exec: executable aws failed with exit code 1
```
[inspection-report-20230502_170548.tar.gz](https://github.com/canonical/microk8s/files/11371545/inspection-report-20230502_170548.tar.gz)

#### Reproduction Steps

1. ...
2. ...

**Comment by khteh** [comment]
Upgrade `awscli` to the latest version
