### ISSUE TITLE
new node fails to join cluster - missing file

### ISSUE THREAD

**Issue by javacruft** [canonical/microk8s#4011]
#### Summary

New node fails to join cluster - errors due to a missing file.

#### What Should Happen Instead?

Great to get it to join the cluster.

#### Reproduction Steps

```
$ sudo microk8s join 10.246.114.14:25000/8d9f10255dddc6a8eb7e3b108c3b7e2c/af562a782d00
Contacting cluster at 10.246.114.14
Traceback (most recent call last):
  File "/snap/microk8s/5222/scripts/wrappers/join.py", line 980, in <module>
    join(prog_name="microk8s join")
  File "/snap/microk8s/5222/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/snap/microk8s/5222/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/snap/microk8s/5222/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/microk8s/5222/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/snap/microk8s/5222/scripts/wrappers/join.py", line 973, in join
    join_dqlite(connection_parts, verify, worker)
  File "/snap/microk8s/5222/scripts/wrappers/join.py", line 768, in join_dqlite
    join_dqlite_master_node(info, master_ip, token)
  File "/snap/microk8s/5222/scripts/wrappers/join.py", line 881, in join_dqlite_master_node
    update_dqlite(info["cluster_cert"], info["cluster_key"], info["voters"], hostname_override)
  File "/snap/microk8s/5222/scripts/wrappers/join.py", line 693, in update_dqlite
    with open("{}/info.yaml".format(cluster_backup_dir)) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/snap/microk8s/5222/var/kubernetes/backend.backup/info.yaml'
```
#### Introspection Report

See bug #4010 for the inspect tarball from the bootstrap node.

**Comment by neoaggelos** [comment]
This looks like the second MicroK8s has not yet had time to bootstrap itself. Can you check if adding a

```
microk8s status --wait-ready --timeout=10
```

helps with the issue?
