### ISSUE TITLE
Join cluster with kube-ovn enabled fails

### ISSUE THREAD

**Issue by emalzer** [canonical/microk8s#4061]
#### Summary
Installing microk8s and enable kube-ovn afterwards works, but joining the nodes to build a cluster fails
Some informations about my setup :

OS : Ubuntu 20.04 LTS
Snap version : 2.59.5
MicroK8s channel : 1.27/stable

#### What Should Happen Instead?
joining a cluster sucessfully.

#### Reproduction Steps
Prep nodes:
1. `snap install microk8s --classic --channel=1.27/stable`
2. `microk8s enable kube-ovn --force`
3. wait for kube-ovn to settle and then joining the nodes brings then the following error:
```
# microk8s join 10.0.31.72:25000/11d8000ec66ea79eee24f04c4fee9a88/bbeb88e587ae
WARNING: Hostpath storage is enabled and is not suitable for multi node clusters.

Contacting cluster at 10.0.31.72
Waiting for this node to finish joining the cluster. .. .. .. ..
Traceback (most recent call last):
  File "/snap/microk8s/5372/scripts/wrappers/join.py", line 1033, in <module>
    join(prog_name="microk8s join")
  File "/snap/microk8s/5372/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/snap/microk8s/5372/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/snap/microk8s/5372/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/microk8s/5372/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/snap/microk8s/5372/scripts/wrappers/join.py", line 1024, in join
    join_dqlite(connection_parts, verify, worker)
  File "/snap/microk8s/5372/scripts/wrappers/join.py", line 785, in join_dqlite
    join_dqlite_master_node(info, master_ip, token)
  File "/snap/microk8s/5372/scripts/wrappers/join.py", line 901, in join_dqlite_master_node
    try_initialise_cni_autodetect_for_clustering(master_ip, apply_cni=False)
  File "/snap/microk8s/5372/scripts/wrappers/common/cluster/utils.py", line 309, in try_initialise_cni_autodetect_for_clustering
    if cni_is_patched():
  File "/snap/microk8s/5372/scripts/wrappers/common/cluster/utils.py", line 276, in cni_is_patched
    with open(yaml) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/snap/microk8s/5372/args/cni-network/cni.yaml'
```
aftewards, running `microk8s status` on this node brings 
```
# microk8s status
microk8s is not running. Use microk8s inspect for a deeper inspection.
```
calling kubectl binrgs:
```
# microk8s kubectl get nodes
Unable to connect to the server: tls: failed to verify certificate: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "10.152.183.1")
```

#### Introspection Report
[inspection-report-20230703_215301.tar.gz](https://github.com/canonical/microk8s/files/11940619/inspection-report-20230703_215301.tar.gz)

**Comment by neoaggelos** [comment]
Hi @emalzer 

Indeed, this looks like a bug that has slipped through. As a temporary workaround, can you try `touch /var/snap/microk8s/current/args/cni-network/cni.yaml` before running the join command? Thanks!

**Comment by emalzer** [comment]
Hi @neoaggelos 

yes, with this the join works. It seems that the cluster works, though I see two errors:

1) 
```<30>2023-07-04T20:01:27+02:00 gs-dev01.ong.lab microk8s.daemon-cluster-agent[1253184]: 2023/07/04 20:01:27 WARNING: failed to update cni configuration: "failed to apply cni configuration: failed after 20 retries: command [/snap/microk8s/5372/microk8s-kubectl.wrapper apply -f /var/snap/microk8s/5372/args/cni-network/cni.yaml] failed with exit code 1: exit status 1"```
I see this only on the master node and two times, looks like for every join of the two other nodes.

2)
```<30>2023-07-04T20:12:30+02:00 gs-dev01.ong.lab microk8s.daemon-apiserver-kicker[728043]: error: the server doesn't have a resource type "felixconfigurations"```
I see this on every node every 5 seconds.

I can't tell if this has an impact or not.

**Comment by neoaggelos** [comment]
Hi @emalzer 

1. Yes, this looks like a bug. it should not break things, other than cause delays when adding cluster nodes.

2. this does look like a bug. i imagine it will persist trying to patch calico offloading, which should probably be avoided.

Thanks for both points, we will prioritize and fix them soon.

**Comment by sachinkumarsingh092** [comment]
This issue is fixed by https://github.com/canonical/microk8s/pull/4132. Closing this now.
