### ISSUE TITLE
Unable to Launch Dashboard on Mac Ventura (M1 Max)

### ISSUE THREAD

**Issue by radhikapc** [canonical/microk8s#4295]
#### Summary

I am unable to launch the microk8s dashboard

#### What Should Happen Instead?

The error I am seeing

```
% microk8s dashboard-proxy  
Checking if Dashboard is running.
Cannot find the dashboard secret.
An unexpected error occurred.
sequence item 10: expected str instance, NoneType found
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/microk8s/2.3.4/libexec/lib/python3.11/site-packages/cli/microk8s.py", line 58, in cli
    dashboard_proxy()
  File "/opt/homebrew/Cellar/microk8s/2.3.4/libexec/lib/python3.11/site-packages/cli/microk8s.py", line 322, in dashboard_proxy
    output = instance.run(command, hide_output=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/microk8s/2.3.4/libexec/lib/python3.11/site-packages/vm_providers/_multipass/_multipass.py", line 54, in run
    return self._multipass_cmd.execute(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/microk8s/2.3.4/libexec/lib/python3.11/site-packages/vm_providers/_multipass/_multipass_command.py", line 232, in execute
    output = _run_output(cmd)
             ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/microk8s/2.3.4/libexec/lib/python3.11/site-packages/vm_providers/_multipass/_multipass_command.py", line 38, in _run_output
    logger.debug("Running {}".format(" ".join(command)))
                                     ^^^^^^^^^^^^^^^^^
TypeError: sequence item 10: expected str instance, NoneType found
None
```

#### Reproduction Steps

1 Install and start microk8s
2. Enable Dahboard
3. Run `microk8s dashboard-proxy`

**Comment by neoaggelos** [comment]
Hi @radhikapc, unfortunately I'm not able to reproduce the issue.

Which MicroK8s version are you running? Can you share the output of the following commands?

```
microk8s kubectl get node -o wide
microk8s kubectl get pod,secret -A -o wide
```

In any case, I believe you should be able to get around the issue by creating this secret:

```
microk8s kubectl apply -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: microk8s-dashboard-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: "default"
type: kubernetes.io/service-account-token
```

Then rerun the `microk8s dashboard-proxy` command.

Finally, I have opened https://github.com/canonical/microk8s/pull/4299 which should help resolve this issue by using a simpler way to retrieve the token
