### ISSUE TITLE
microk8s status --wait-ready hanging

### ISSUE THREAD

**Issue by Arthur378** [canonical/microk8s#4576]
In the process of installing microk8s, I use `microk8s status --wait-ready` command at one stage, but after many minutes, there is no answer and use ctrl + c  :

```
Traceback (most recent call last):
  File "/snap/microk8s/6876/scripts/wrappers/status.py", line 212, in <module>
    is_ready = wait_for_ready(timeout)
  File "/snap/microk8s/6876/scripts/wrappers/common/utils.py", line 198, in wait_for_ready
    time.sleep(2)
KeyboardInterrupt
```

`microk8s inspect`:

```
Inspecting system
WARNING:  The hostname of this server is 'Arthur-Desktop'.
Having uppercase letters in the hostname may cause issues with RBAC.
Consider changing the hostname to only have lowercase letters with:

    hostnamectl set-hostname arthur-desktop
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-kubelite is running
  Service snap.microk8s.daemon-k8s-dqlite is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy openSSL information to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy asnycio usage and limits to the final report tarball
  Copy inotify max_user_instances and max_user_watches to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
Inspecting dqlite
  Inspect dqlite
cp: cannot stat '/var/snap/microk8s/6876/var/kubernetes/backend/localnode.yaml': No such file or directory

WARNING:  Docker is installed.
File "/etc/docker/daemon.json" does not exist.
You should create it and add the following lines:
{
    "insecure-registries" : ["localhost:32000"]
}
and then restart docker with: sudo systemctl restart docker
WARNING:  This machine's hostname contains capital letters and/or underscores.
          This is not a valid name for a Kubernetes node, causing node registration to fail.
          Please change the machine's hostname or refer to the documentation for more details:
          https://microk8s.io/docs/troubleshooting#heading--common-issues
Building the report tarball
  Report tarball is at /var/snap/microk8s/6876/inspection-report-20240718_093640.tar.gz
```
  
How do I fix the problem?

**Comment by ktsakalozos** [comment]
Hi @Arthur378 most probably the API server fails to start can you please attach the inspection tarball  (/var/snap/microk8s/6876/inspection-report-20240718_093640.tar.gz)  so we can look at the logs?

**Comment by jrleader** [comment]
Hi, I am also experiencing this issue. The command output is exactly the same as the one @Arthur378 had shared. I tried to run "microk8s kubectl get nodes" and the output suggests the master node is not ready (Please refer to the screenshot attached

![Image](https://github.com/user-attachments/assets/eb4b8c90-c404-4e87-b4d0-ef4055d37a23)

). How to fix this issue? Need help, appreciated.

**Comment by nmusatti** [comment]
I'm experiencing the same problem with 1.35 installed after removing a previous installation. In my case
"microk8s status --wait-ready" hangs indefinitely (over an hour at least);
"microk8s kubectl get nodes" returns "No resources found";
"microk8s kubectl get namespace" lists the system namespaces;
"microk8s kubectl get pods -A" returns "No resources found".
Every now and then kubectl returns "The connection to the server 127.0.0.1:16443 was refused - did you specify the right host or port?"
This is on Ubuntu 20.04.6 LTS. Performing the same operation on a different server, running Ubuntu 22.04.5 LTS caused no problem at all.

**Comment by nmusatti** [comment]
While inspecting logs I noticed that kubelite kept failing and restarting due to a problem of incompatibility with cgroups v.1. So I decided to upgrade my server to 22.04 LTS. This solved my problem.
